In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("C:/Users/Admin/Desktop/bundesliga-players-mongodb/data/bundesliga_player.csv")

DATA PREPROCESSING

In [3]:
df

,Unnamed: 0,name,full_name,age,height,nationality,place_of_birth,price,max_price,position,shirt_nr,foot,club,contract_expires,joined_club,player_agent,outfitter
0,0,Manuel Neuer,Manuel Peter Neuer,37,1.93,Germany,Gelsenkirchen,7.00,45.0,Goalkeeper,1,right,Bayern Munich,2024-06-30,2011-07-01,PRO Profil GmbH,adidas
1,1,Yann Sommer,NaN,34,1.83,Switzerland,Morges,5.00,13.0,Goalkeeper,27,right,Bayern Munich,2025-06-30,2023-01-19,Relatives,Puma
2,2,Sven Ulreich,NaN,34,1.92,Germany,Schorndorf,0.90,6.0,Goalkeeper,26,right,Bayern Munich,2024-06-30,2021-07-01,BMS Sportconsulting ...,adidas
3,3,Johannes Schenk,NaN,20,1.91,Germany,Schweinfurt,0.30,0.3,Goalkeeper,35,NaN,Bayern Munich,2024-06-30,2022-07-01,11WINS,NaN
4,4,Matthijs de Ligt,NaN,23,1.89,Netherlands,Leiderdorp,75.00,75.0,Defender - Centre-Back,4,right,Bayern Munich,2027-06-30,2022-07-19,Rafaela Pimenta,adidas
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
510,510,Takuma Asano,浅野 拓磨,28,1.73,Japan,"Komono, Mie",4.00,4.0,Attack - Right Winger,11,right,VfL Bochum,2024-06-30,2021-07-01,JEB ENTERTAINMENT ...,adidas
511,511,Philipp Hofmann,NaN,30,1.95,Germany,Arnsberg,2.50,2.5,Attack - Centre-Forward,33,left,VfL Bochum,2024-06-30,2022-07-01,ROOF,NaN
512,512,Simon Zoller,Simon Martin Zoller,31,1.79,Germany,Friedrichshafen,1.10,3.0,Attack - Centre-Forward,9,right,VfL Bochum,2024-06-30,2019-01-01,GoalSky,Puma
513,513,Silvère Ganvoula,Silvère Ganvoula M'boussy,26,1.91,Congo,Brazzaville,0.75,2.5,Attack - Centre-Forward,35,right,VfL Bochum,2023-06-30,2019-07-05,BY Sport Consulting,Puma
514,514,Moritz Broschinski,NaN,22,1.90,Germany,Finsterwalde,0.50,0.5,Attack - Centre-Forward,29,right,VfL Bochum,2026-06-30,2023-01-22,Teamgeist ...,NaN

In [4]:
df.drop(["Unnamed: 0", "full_name", "max_price", "shirt_nr", "foot", "contract_expires", "joined_club",	"player_agent",	"outfitter"], axis=1, inplace = True)

In [5]:
df

,name,age,height,nationality,place_of_birth,price,position,club
0,Manuel Neuer,37,1.93,Germany,Gelsenkirchen,7.00,Goalkeeper,Bayern Munich
1,Yann Sommer,34,1.83,Switzerland,Morges,5.00,Goalkeeper,Bayern Munich
2,Sven Ulreich,34,1.92,Germany,Schorndorf,0.90,Goalkeeper,Bayern Munich
3,Johannes Schenk,20,1.91,Germany,Schweinfurt,0.30,Goalkeeper,Bayern Munich
4,Matthijs de Ligt,23,1.89,Netherlands,Leiderdorp,75.00,Defender - Centre-Back,Bayern Munich
...,...,...,...,...,...,...,...,...
510,Takuma Asano,28,1.73,Japan,"Komono, Mie",4.00,Attack - Right Winger,VfL Bochum
511,Philipp Hofmann,30,1.95,Germany,Arnsberg,2.50,Attack - Centre-Forward,VfL Bochum
512,Simon Zoller,31,1.79,Germany,Friedrichshafen,1.10,Attack - Centre-Forward,VfL Bochum
513,Silvère Ganvoula,26,1.91,Congo,Brazzaville,0.75,Attack - Centre-Forward,VfL Bochum
514,Moritz Broschinski,22,1.90,Germany,Finsterwalde,0.50,Attack - Centre-Forward,VfL Bochum

In [6]:
df.shape

(515, 8)

In [7]:
df.columns = [col.strip().lower().replace(" ", "_") for col in df.columns]

In [8]:
df.dtypes

name                  str
age                 int64
height            float64
nationality           str
place_of_birth        str
price             float64
position              str
club                  str
dtype: object

In [9]:
count = 0
for col in df.columns:
    if df[col].dtype == object:
        df[col] = df[col].astype(str).str.strip()
        count += 1
print(f"{count} changes have been made")

0 changes have been made

In [10]:
df[df.isna().any(axis=1)]

,name,age,height,nationality,place_of_birth,price,position,club
65,Oskar Preil,19,1.87,Germany,NaN,NaN,Goalkeeper,RB Leipzig
126,Aurélio Buta,26,1.72,Portugal Angola,NaN,6.0,Defender - Right-Back,E. Frankfurt
143,Nacho Ferri,18,1.92,Spain,Montaverner,NaN,Attack - Centre-Forward,E. Frankfurt
156,Simon Walde,18,1.85,Germany,Düsseldorf,NaN,Defender - Right-Back,Bor. M'gladbach
173,Philipp Schulze,20,1.90,Germany,NaN,0.2,Goalkeeper,VfL Wolfsburg
299,Arne Engels,19,1.85,Belgium,NaN,3.5,midfield - Central Midfield,FC Augsburg
301,Mert Kömür,17,1.83,Germany Turkey,Dachau,NaN,midfield - Attacking Midfield,FC Augsburg U19
348,Philipp Schulz,17,1.88,Germany,NaN,0.3,Defender - Centre-Back,1.FSV Mainz 05
377,Elias Bakatukanda,19,1.93,Germany DR Congo,Köln,NaN,Defender - Centre-Back,1.FC Köln U19

In [11]:
df.isna().sum()

name              0
age               0
height            0
nationality       0
place_of_birth    5
price             5
position          0
club              0
dtype: int64

In [12]:
df.index.nunique()

515

In [13]:
df.position = df.position.apply(lambda x : x.replace(" ", ""))

In [14]:
df.position.unique()

<StringArray>
[                'Goalkeeper',       'Defender-Centre-Back',
         'Defender-Left-Back',        'Defender-Right-Back',
 'midfield-DefensiveMidfield',   'midfield-CentralMidfield',
 'midfield-AttackingMidfield',          'Attack-LeftWinger',
         'Attack-RightWinger',       'Attack-SecondStriker',
      'Attack-Centre-Forward',     'midfield-RightMidfield',
      'midfield-LeftMidfield']
Length: 13, dtype: str

In [15]:
df.dtypes

name                  str
age                 int64
height            float64
nationality           str
place_of_birth        str
price             float64
position              str
club                  str
dtype: object

In [16]:
df

,name,age,height,nationality,place_of_birth,price,position,club
0,Manuel Neuer,37,1.93,Germany,Gelsenkirchen,7.00,Goalkeeper,Bayern Munich
1,Yann Sommer,34,1.83,Switzerland,Morges,5.00,Goalkeeper,Bayern Munich
2,Sven Ulreich,34,1.92,Germany,Schorndorf,0.90,Goalkeeper,Bayern Munich
3,Johannes Schenk,20,1.91,Germany,Schweinfurt,0.30,Goalkeeper,Bayern Munich
4,Matthijs de Ligt,23,1.89,Netherlands,Leiderdorp,75.00,Defender-Centre-Back,Bayern Munich
...,...,...,...,...,...,...,...,...
510,Takuma Asano,28,1.73,Japan,"Komono, Mie",4.00,Attack-RightWinger,VfL Bochum
511,Philipp Hofmann,30,1.95,Germany,Arnsberg,2.50,Attack-Centre-Forward,VfL Bochum
512,Simon Zoller,31,1.79,Germany,Friedrichshafen,1.10,Attack-Centre-Forward,VfL Bochum
513,Silvère Ganvoula,26,1.91,Congo,Brazzaville,0.75,Attack-Centre-Forward,VfL Bochum
514,Moritz Broschinski,22,1.90,Germany,Finsterwalde,0.50,Attack-Centre-Forward,VfL Bochum

In [17]:
df = df.dropna()

In [18]:
df.price = df.price * 1_000_000

In [19]:
df

,name,age,height,nationality,place_of_birth,price,position,club
0,Manuel Neuer,37,1.93,Germany,Gelsenkirchen,7000000.0,Goalkeeper,Bayern Munich
1,Yann Sommer,34,1.83,Switzerland,Morges,5000000.0,Goalkeeper,Bayern Munich
2,Sven Ulreich,34,1.92,Germany,Schorndorf,900000.0,Goalkeeper,Bayern Munich
3,Johannes Schenk,20,1.91,Germany,Schweinfurt,300000.0,Goalkeeper,Bayern Munich
4,Matthijs de Ligt,23,1.89,Netherlands,Leiderdorp,75000000.0,Defender-Centre-Back,Bayern Munich
...,...,...,...,...,...,...,...,...
510,Takuma Asano,28,1.73,Japan,"Komono, Mie",4000000.0,Attack-RightWinger,VfL Bochum
511,Philipp Hofmann,30,1.95,Germany,Arnsberg,2500000.0,Attack-Centre-Forward,VfL Bochum
512,Simon Zoller,31,1.79,Germany,Friedrichshafen,1100000.0,Attack-Centre-Forward,VfL Bochum
513,Silvère Ganvoula,26,1.91,Congo,Brazzaville,750000.0,Attack-Centre-Forward,VfL Bochum
514,Moritz Broschinski,22,1.90,Germany,Finsterwalde,500000.0,Attack-Centre-Forward,VfL Bochum

In [20]:
df.drop("place_of_birth", axis=1, inplace=True)

In [21]:
df.price = df.price.astype('Int64').map("{:,}".format)

In [22]:
df

,name,age,height,nationality,price,position,club
0,Manuel Neuer,37,1.93,Germany,"7,000,000",Goalkeeper,Bayern Munich
1,Yann Sommer,34,1.83,Switzerland,"5,000,000",Goalkeeper,Bayern Munich
2,Sven Ulreich,34,1.92,Germany,"900,000",Goalkeeper,Bayern Munich
3,Johannes Schenk,20,1.91,Germany,"300,000",Goalkeeper,Bayern Munich
4,Matthijs de Ligt,23,1.89,Netherlands,"75,000,000",Defender-Centre-Back,Bayern Munich
...,...,...,...,...,...,...,...
510,Takuma Asano,28,1.73,Japan,"4,000,000",Attack-RightWinger,VfL Bochum
511,Philipp Hofmann,30,1.95,Germany,"2,500,000",Attack-Centre-Forward,VfL Bochum
512,Simon Zoller,31,1.79,Germany,"1,100,000",Attack-Centre-Forward,VfL Bochum
513,Silvère Ganvoula,26,1.91,Congo,"750,000",Attack-Centre-Forward,VfL Bochum
514,Moritz Broschinski,22,1.90,Germany,"500,000",Attack-Centre-Forward,VfL Bochum

In [23]:
countries = ["Afghanistan","Albania","Algeria","Angola","Argentina","Armenia","Austria","Australia","Barbados","Belgium","Bosnia-Herzegovina","Brazil","Bulgaria","Burkina Faso","Cameroon","Canada","Cape Verde","Colombia","Congo","Costa Rica","Croatia","Czech Republic","Denmark","Dominican Republic","DR Congo","Ecuador","Egypt","England","Finland","France","Gambia","Germany","Ghana","Greece","Guadeloupe","Guinea","Guinea-Bissau","Hungary","Iran","Ireland","Israel","Italy","Jamaica","Japan","Kenya","Kosovo","Korea, South","Liberia","Luxembourg","Mali","Malta","Martinique","Montenegro","Morocco","Netherlands","Nigeria","Norway","Philippines","Poland","Portugal","Réunion","Russia","Saudi Arabia","Senegal","Serbia","Slovakia","Slovenia","South Korea","Southern Sudan","Spain","Suriname","Sweden","Switzerland","Syria","Tanzania","Togo","Tunisia","Turkey","Ukraine","United States","Uruguay"]

In [24]:
def extract_countries(text):
    text = " ".join(text.split())
    found = []

    for country in sorted(countries, key=len, reverse=True):
        if country in text:
            found.append(country)
            text = text.replace(country, "").strip()

    return found

df["countries"] = df["nationality"].apply(extract_countries)

In [25]:
df

,name,age,height,nationality,price,position,club,countries
0,Manuel Neuer,37,1.93,Germany,"7,000,000",Goalkeeper,Bayern Munich,[Germany]
1,Yann Sommer,34,1.83,Switzerland,"5,000,000",Goalkeeper,Bayern Munich,[Switzerland]
2,Sven Ulreich,34,1.92,Germany,"900,000",Goalkeeper,Bayern Munich,[Germany]
3,Johannes Schenk,20,1.91,Germany,"300,000",Goalkeeper,Bayern Munich,[Germany]
4,Matthijs de Ligt,23,1.89,Netherlands,"75,000,000",Defender-Centre-Back,Bayern Munich,[Netherlands]
...,...,...,...,...,...,...,...,...
510,Takuma Asano,28,1.73,Japan,"4,000,000",Attack-RightWinger,VfL Bochum,[Japan]
511,Philipp Hofmann,30,1.95,Germany,"2,500,000",Attack-Centre-Forward,VfL Bochum,[Germany]
512,Simon Zoller,31,1.79,Germany,"1,100,000",Attack-Centre-Forward,VfL Bochum,[Germany]
513,Silvère Ganvoula,26,1.91,Congo,"750,000",Attack-Centre-Forward,VfL Bochum,[Congo]
514,Moritz Broschinski,22,1.90,Germany,"500,000",Attack-Centre-Forward,VfL Bochum,[Germany]

In [26]:
print(df.loc[5, "countries"])

['Guinea-Bissau', 'France']

In [29]:
# We You flatten the lists to check unique countries.
df_exploded = df["countries"].explode()
unique_countries = df_exploded.unique()
print(unique_countries)

<StringArray>
[           'Germany',        'Switzerland',        'Netherlands',
      'Guinea-Bissau',             'France',              'Spain',
            'Liberia',             'Canada',           'Portugal',
            'Morocco',            'Croatia',            'Senegal',
           'Suriname',            'England',            'Austria',
             'Kosovo',         'Guadeloupe',           'Cameroon',
             'Poland',               'Mali',             'Greece',
             'Norway',            'Belgium',             'Turkey',
             'Guinea',              'Syria',      'United States',
            'Nigeria',           'Barbados',         'Martinique',
            'Hungary',              'Ghana',           'Slovenia',
             'Sweden',           'DR Congo',           'Tanzania',
            'Denmark',           'Slovakia',            'Finland',
             'Russia',       'Burkina Faso',            'Ecuador',
                  nan,          'Argentina',        'Afghanistan',
     'Czech Republic',               'Iran',            'Albania',
             'Brazil',              'Japan',               'Togo',
           'Colombia',              'Italy',            'Algeria',
            'Ireland',         'Cape Verde',         'Luxembourg',
 'Dominican Republic',              'Egypt',         'Montenegro',
       'Korea, South', 'Bosnia-Herzegovina',             'Israel',
            'Tunisia',             'Serbia',            'Jamaica',
              'Malta',     'Southern Sudan',          'Australia',
             'Angola',            'Réunion',              'Kenya',
            'Armenia',            'Uruguay',           'Bulgaria',
            'Ukraine',             'Gambia',         'Costa Rica',
        'Philippines',              'Congo']
Length: 80, dtype: str

In [31]:
df.drop("nationality", axis=1, inplace=True)

In [32]:
df

,name,age,height,price,position,club,countries
0,Manuel Neuer,37,1.93,"7,000,000",Goalkeeper,Bayern Munich,[Germany]
1,Yann Sommer,34,1.83,"5,000,000",Goalkeeper,Bayern Munich,[Switzerland]
2,Sven Ulreich,34,1.92,"900,000",Goalkeeper,Bayern Munich,[Germany]
3,Johannes Schenk,20,1.91,"300,000",Goalkeeper,Bayern Munich,[Germany]
4,Matthijs de Ligt,23,1.89,"75,000,000",Defender-Centre-Back,Bayern Munich,[Netherlands]
...,...,...,...,...,...,...,...
510,Takuma Asano,28,1.73,"4,000,000",Attack-RightWinger,VfL Bochum,[Japan]
511,Philipp Hofmann,30,1.95,"2,500,000",Attack-Centre-Forward,VfL Bochum,[Germany]
512,Simon Zoller,31,1.79,"1,100,000",Attack-Centre-Forward,VfL Bochum,[Germany]
513,Silvère Ganvoula,26,1.91,"750,000",Attack-Centre-Forward,VfL Bochum,[Congo]
514,Moritz Broschinski,22,1.90,"500,000",Attack-Centre-Forward,VfL Bochum,[Germany]

INSERTING DATA TO MONGODB

In [33]:
df.price = df.price.str.replace(",", "", regex=False).astype("Int64")

In [34]:
records = df.to_dict(orient='records')

In [35]:
records

[{'name': 'Manuel Neuer',
  'age': 37,
  'height': 1.93,
  'price': 7000000,
  'position': 'Goalkeeper',
  'club': 'Bayern Munich',
  'countries': ['Germany']},
 {'name': 'Yann Sommer',
  'age': 34,
  'height': 1.83,
  'price': 5000000,
  'position': 'Goalkeeper',
  'club': 'Bayern Munich',
  'countries': ['Switzerland']},
 {'name': 'Sven Ulreich',
  'age': 34,
  'height': 1.92,
  'price': 900000,
  'position': 'Goalkeeper',
  'club': 'Bayern Munich',
  'countries': ['Germany']},
 {'name': 'Johannes Schenk',
  'age': 20,
  'height': 1.91,
  'price': 300000,
  'position': 'Goalkeeper',
  'club': 'Bayern Munich',
  'countries': ['Germany']},
 {'name': 'Matthijs de Ligt',
  'age': 23,
  'height': 1.89,
  'price': 75000000,
  'position': 'Defender-Centre-Back',
  'club': 'Bayern Munich',
  'countries': ['Netherlands']},
 {'name': 'Dayot Upamecano',
  'age': 24,
  'height': 1.86,
  'price': 60000000,
  'position': 'Defender-Centre-Back',
  'club': 'Bayern Munich',
  'countries': ['Guinea-Bissau', 'France']},
 {'name': 'Lucas Hernández',
  'age': 27,
  'height': 1.84,
  'price': 50000000,
  'position': 'Defender-Centre-Back',
  'club': 'Bayern Munich',
  'countries': ['France', 'Spain']},
 {'name': 'Alphonso Davies',
  'age': 22,
  'height': 1.85,
  'price': 70000000,
  'position': 'Defender-Left-Back',
  'club': 'Bayern Munich',
  'countries': ['Liberia', 'Canada']},
 {'name': 'Daley Blind',
  'age': 33,
  'height': 1.8,
  'price': 6000000,
  'position': 'Defender-Left-Back',
  'club': 'Bayern Munich',
  'countries': ['Netherlands']},
 {'name': 'João Cancelo',
  'age': 28,
  'height': 1.82,
  'price': 60000000,
  'position': 'Defender-Right-Back',
  'club': 'Bayern Munich',
  'countries': ['Portugal']},
 {'name': 'Benjamin Pavard',
  'age': 27,
  'height': 1.86,
  'price': 35000000,
  'position': 'Defender-Right-Back',
  'club': 'Bayern Munich',
  'countries': ['France']},
 {'name': 'Noussair Mazraoui',
  'age': 25,
  'height': 1.83,
  'price': 28000000,
  'position': 'Defender-Right-Back',
  'club': 'Bayern Munich',
  'countries': ['Netherlands', 'Morocco']},
 {'name': 'Josip Stanisic',
  'age': 23,
  'height': 1.87,
  'price': 12000000,
  'position': 'Defender-Right-Back',
  'club': 'Bayern Munich',
  'countries': ['Croatia', 'Germany']},
 {'name': 'Bouna Sarr',
  'age': 31,
  'height': 1.77,
  'price': 2500000,
  'position': 'Defender-Right-Back',
  'club': 'Bayern Munich',
  'countries': ['Senegal', 'France']},
 {'name': 'Joshua Kimmich',
  'age': 28,
  'height': 1.77,
  'price': 80000000,
  'position': 'midfield-DefensiveMidfield',
  'club': 'Bayern Munich',
  'countries': ['Germany']},
 {'name': 'Leon Goretzka',
  'age': 28,
  'height': 1.89,
  'price': 65000000,
  'position': 'midfield-CentralMidfield',
  'club': 'Bayern Munich',
  'countries': ['Germany']},
 {'name': 'Ryan Gravenberch',
  'age': 20,
  'height': 1.9,
  'price': 30000000,
  'position': 'midfield-CentralMidfield',
  'club': 'Bayern Munich',
  'countries': ['Netherlands', 'Suriname']},
 {'name': 'Jamal Musiala',
  'age': 20,
  'height': 1.84,
  'price': 110000000,
  'position': 'midfield-AttackingMidfield',
  'club': 'Bayern Munich',
  'countries': ['England', 'Germany']},
 {'name': 'Paul Wanner',
  'age': 17,
  'height': 1.85,
  'price': 3000000,
  'position': 'midfield-AttackingMidfield',
  'club': 'Bayern Munich',
  'countries': ['Austria', 'Germany']},
 {'name': 'Arijon Ibrahimovic',
  'age': 17,
  'height': 1.76,
  'price': 1000000,
  'position': 'midfield-AttackingMidfield',
  'club': 'Bayern Munich',
  'countries': ['Germany', 'Kosovo']},
 {'name': 'Kingsley Coman',
  'age': 26,
  'height': 1.81,
  'price': 65000000,
  'position': 'Attack-LeftWinger',
  'club': 'Bayern Munich',
  'countries': ['Guadeloupe', 'France']},
 {'name': 'Sadio Mané',
  'age': 31,
  'height': 1.74,
  'price': 45000000,
  'position': 'Attack-LeftWinger',
  'club': 'Bayern Munich',
  'countries': ['Senegal']},
 {'name': 'Leroy Sané',
  'age': 27,
  'height': 1.83,
  'price': 70000000,
  'position': 'Attack-RightWinger',
  'club': 'Bayern Munich',
  'countries': ['Germany', 'France']},
 {'name': 'Serge Gnabry',
  'age': 27,
  'height': 1.76,
  'price': 55000000,
  'position': 'Attack-RightWinger',
  'club': 'Bayern Munich',
  'countries': ['Germany']},
 {'name': 'Thomas Müller',
  'age': 33,
  'height': 1.85,
  'price': 18000000,
  'position': 'Attack-SecondStriker',
  'club': 'Bayern Munich',
  'countries': ['Germany']},
 {'name': 'Mathys Tel',
  'age': 18,
  'height': 1.83,
  'price': 20000000,
  'position': 'Attack-Centre-Forward',
  'club': 'Bayern Munich',
  'countries': ['Guadeloupe', 'France']},
 {'name': 'Eric Maxim Choupo-Moting',
  'age': 34,
  'height': 1.91,
  'price': 6000000,
  'position': 'Attack-Centre-Forward',
  'club': 'Bayern Munich',
  'countries': ['Cameroon', 'Germany']},
 {'name': 'Gregor Kobel',
  'age': 25,
  'height': 1.94,
  'price': 35000000,
  'position': 'Goalkeeper',
  'club': 'Bor. Dortmund',
  'countries': ['Switzerland']},
 {'name': 'Marcel Lotka',
  'age': 21,
  'height': 1.9,
  'price': 1300000,
  'position': 'Goalkeeper',
  'club': 'Bor. Dortmund',
  'countries': ['Germany', 'Poland']},
 {'name': 'Alexander Meyer',
  'age': 32,
  'height': 1.95,
  'price': 1000000,
  'position': 'Goalkeeper',
  'club': 'Bor. Dortmund',
  'countries': ['Germany']},
 {'name': 'Luca Unbehaun',
  'age': 22,
  'height': 1.85,
  'price': 1000000,
  'position': 'Goalkeeper',
  'club': 'Bor. Dortmund',
  'countries': ['Germany']},
 {'name': 'Nico Schlotterbeck',
  'age': 23,
  'height': 1.91,
  'price': 40000000,
  'position': 'Defender-Centre-Back',
  'club': 'Bor. Dortmund',
  'countries': ['Germany']},
 {'name': 'Niklas Süle',
  'age': 27,
  'height': 1.95,
  'price': 35000000,
  'position': 'Defender-Centre-Back',
  'club': 'Bor. Dortmund',
  'countries': ['Germany']},
 {'name': 'Mats Hummels',
  'age': 34,
  'height': 1.91,
  'price': 6500000,
  'position': 'Defender-Centre-Back',
  'club': 'Bor. Dortmund',
  'countries': ['Germany']},
 {'name': 'Soumaïla Coulibaly',
  'age': 19,
  'height': 1.9,
  'price': 1000000,
  'position': 'Defender-Centre-Back',
  'club': 'Bor. Dortmund',
  'countries': ['France', 'Mali']},
 {'name': 'Antonios Papadopoulos',
  'age': 23,
  'height': 1.86,
  'price': 600000,
  'position': 'Defender-Centre-Back',
  'club': 'B. Dortmund II',
  'countries': ['Germany', 'Greece']},
 {'name': 'Raphaël Guerreiro',
  'age': 29,
  'height': 1.7,
  'price': 20000000,
  'position': 'Defender-Left-Back',
  'club': 'Bor. Dortmund',
  'countries': ['Portugal', 'France']},
 {'name': 'Tom Rothe',
  'age': 18,
  'height': 1.93,
  'price': 3500000,
  'position': 'Defender-Left-Back',
  'club': 'Bor. Dortmund',
  'countries': ['Germany']},
 {'name': 'Nico Schulz',
  'age': 30,
  'height': 1.8,
  'price': 2000000,
  'position': 'Defender-Left-Back',
  'club': 'Bor. Dortmund',
  'countries': ['Germany']},
 {'name': 'Julian Ryerson',
  'age': 25,
  'height': 1.83,
  'price': 10000000,
  'position': 'Defender-Right-Back',
  'club': 'Bor. Dortmund',
  'countries': ['Norway']},
 {'name': 'Marius Wolf',
  'age': 27,
  'height': 1.87,
  'price': 9000000,
  'position': 'Defender-Right-Back',
  'club': 'Bor. Dortmund',
  'countries': ['Germany']},
 {'name': 'Thomas Meunier',
  'age': 31,
  'height': 1.91,
  'price': 6500000,
  'position': 'Defender-Right-Back',
  'club': 'Bor. Dortmund',
  'countries': ['Belgium']},
 {'name': 'Mateu Morey Bauzà',
  'age': 23,
  'height': 1.73,
  'price': 1500000,
  'position': 'Defender-Right-Back',
  'club': 'Bor. Dortmund',
  'countries': ['Spain']},
 {'name': 'Felix Passlack',
  'age': 24,
  'height': 1.7,
  'price': 1500000,
  'position': 'Defender-Right-Back',
  'club': 'Bor. Dortmund',
  'countries': ['Germany']},
 {'name': 'Salih Özcan',
  'age': 25,
  'height': 1.83,
  'price': 17000000,
  'position': 'midfield-DefensiveMidfield',
  'club': 'Bor. Dortmund',
  'countries': ['Germany', 'Turkey']},
 {'name': 'Emre Can',
  'age': 29,
  'height': 1.86,
  'price': 14000000,
  'position': 'midfield-DefensiveMidfield',
  'club': 'Bor. Dortmund',
  'countries': ['Germany', 'Turkey']},
 {'name': 'Abdoulaye Kamara',
  'age': 18,
  'height': 1.83,
  'price': 1000000,
  'position': 'midfield-DefensiveMidfield',
  'club': 'B. Dortmund II',
  'countries': ['France', 'Guinea']},
 {'name': 'Jude Bellingham',
  'age': 19,
  'height': 1.86,
  'price': 120000000,
  'position': 'midfield-CentralMidfield',
  'club': 'Bor. Dortmund',
  'countries': ['England']},
 {'name': 'Mahmoud Dahoud',
  'age': 27,
  'height': 1.78,
  'price': 12000000,
  'position': 'midfield-CentralMidfield',
  'club': 'Bor. Dortmund',
  'countries': ['Germany', 'Syria']},
 {'name': 'Julian Brandt',
  'age': 27,
  'height': 1.85,
  'price': 40000000,
  'position': 'midfield-AttackingMidfield',
  'club': 'Bor. Dortmund',
  'countries': ['Germany']},
 {'name': 'Giovanni Reyna',
  'age': 20,
  'height': 1.85,
  'price': 28000000,
  'position': 'midfield-AttackingMidfield',
  'club': 'Bor. Dortmund',
  'countries': ['United States', 'Portugal']},
 {'name': 'Marco Reus',
  'age': 33,
  'height': 1.8,
  'price': 9000000,
  'position': 'midfield-AttackingMidfield',
  'club': 'Bor. Dortmund',
  'countries': ['Germany']},
 {'name': 'Göktan Gürpüz',
  'age': 20,
  'height': 1.76,
  'price': 300000,
  'position': 'midfield-AttackingMidfield',
  'club': 'B. Dortmund II',
  'countries': ['Germany', 'Turkey']},
 {'name': 'Karim Adeyemi',
  'age': 21,
  'height': 1.8,
  'price': 35000000,
  'position': 'Attack-LeftWinger',
  'club': 'Bor. Dortmund',
  'countries': ['Germany', 'Nigeria']},
 {'name': 'Jamie Bynoe-Gittens',
  'age': 18,
  'height': 1.77,
  'price': 14000000,
  'position': 'Attack-LeftWinger',
  'club': 'Bor. Dortmund',
  'countries': ['Barbados', 'England']},
 {'name': 'Donyell Malen',
  'age': 24,
  'height': 1.78,
  'price': 16000000,
  'position': 'Attack-RightWinger',
  'club': 'Bor. Dortmund',
  'countries': ['Netherlands', 'Suriname']},
 {'name': 'Julien Duranville',
  'age': 17,
  'height': 1.7,
  'price': 5000000,
  'position': 'Attack-RightWinger',
  'club': 'Bor. Dortmund',
  'countries': ['Belgium']},
 {'name': 'Sébastien Haller',
  'age': 28,
  'height': 1.91,
  'price': 30000000,
  'position': 'Attack-Centre-Forward',
  'club': 'Bor. Dortmund',
  'countries': ['France']},
 {'name': 'Youssoufa Moukoko',
  'age': 18,
  'height': 1.79,
  'price': 30000000,
  'position': 'Attack-Centre-Forward',
  'club': 'Bor. Dortmund',
  'countries': ['Cameroon', 'Germany']},
 {'name': 'Anthony Modeste',
  'age': 35,
  'height': 1.88,
  'price': 1000000,
  'position': 'Attack-Centre-Forward',
  'club': 'Bor. Dortmund',
  'countries': ['Martinique', 'France']},
 {'name': 'Péter Gulácsi',
  'age': 33,
  'height': 1.9,
  'price': 6000000,
  'position': 'Goalkeeper',
  'club': 'RB Leipzig',
  'countries': ['Hungary']},
 {'name': 'Janis Blaswich',
  'age': 32,
  'height': 1.93,
  'price': 2000000,
  'position': 'Goalkeeper',
  'club': 'RB Leipzig',
  'countries': ['Germany']},
 {'name': 'Örjan Nyland',
  'age': 32,
  'height': 1.92,
  'price': 600000,
  'position': 'Goalkeeper',
  'club': 'RB Leipzig',
  'countries': ['Norway']},
 {'name': 'Jonas Nickisch',
  'age': 18,
  'height': 1.9,
  'price': 200000,
  'position': 'Goalkeeper',
  'club': 'RB Leipzig U19',
  'countries': ['Germany']},
 {'name': 'Timo Schlieck',
  'age': 17,
  'height': 1.95,
  'price': 200000,
  'position': 'Goalkeeper',
  'club': 'RB Leipzig U17',
  'countries': ['Germany']},
 {'name': 'Josko Gvardiol',
  'age': 21,
  'height': 1.85,
  'price': 75000000,
  'position': 'Defender-Centre-Back',
  'club': 'RB Leipzig',
  'countries': ['Croatia']},
 {'name': 'Mohamed Simakan',
  'age': 23,
  'height': 1.87,
  'price': 28000000,
  'position': 'Defender-Centre-Back',
  'club': 'RB Leipzig',
  'countries': ['France', 'Guinea']},
 {'name': 'Abdou Diallo',
  'age': 27,
  'height': 1.87,
  'price': 15000000,
  'position': 'Defender-Centre-Back',
  'club': 'RB Leipzig',
  'countries': ['Senegal', 'France']},
 {'name': 'Willi Orbán',
  'age': 30,
  'height': 1.86,
  'price': 10000000,
  'position': 'Defender-Centre-Back',
  'club': 'RB Leipzig',
  'countries': ['Germany', 'Hungary']},
 {'name': 'David Raum',
  'age': 25,
  'height': 1.8,
  'price': 20000000,
  'position': 'Defender-Left-Back',
  'club': 'RB Leipzig',
  'countries': ['Germany']},
 {'name': 'Marcel Halstenberg',
  'age': 31,
  'height': 1.88,
  'price': 4000000,
  'position': 'Defender-Left-Back',
  'club': 'RB Leipzig',
  'countries': ['Germany']},
 {'name': 'Sanoussy Ba',
  'age': 19,
  'height': 1.84,
  'price': 500000,
  'position': 'Defender-Left-Back',
  'club': 'RB Leipzig',
  'countries': ['Germany', 'Senegal']},
 {'name': 'Benjamin Henrichs',
  'age': 26,
  'height': 1.85,
  'price': 15000000,
  'position': 'Defender-Right-Back',
  'club': 'RB Leipzig',
  'countries': ['Germany', 'Ghana']},
 {'name': 'Lukas Klostermann',
  'age': 26,
  'height': 1.89,
  'price': 12000000,
  'position': 'Defender-Right-Back',
  'club': 'RB Leipzig',
  'countries': ['Germany']},
 {'name': 'Konrad Laimer',
  'age': 25,
  'height': 1.8,
  'price': 28000000,
  'position': 'midfield-CentralMidfield',
  'club': 'RB Leipzig',
  'countries': ['Austria']},
 {'name': 'Xaver Schlager',
  'age': 25,
  'height': 1.74,
  'price': 22000000,
  'position': 'midfield-CentralMidfield',
  'club': 'RB Leipzig',
  'countries': ['Austria']},
 {'name': 'Amadou Haidara',
  'age': 25,
  'height': 1.75,
  'price': 17000000,
  'position': 'midfield-CentralMidfield',
  'club': 'RB Leipzig',
  'countries': ['Mali']},
 {'name': 'Kevin Kampl',
  'age': 32,
  'height': 1.78,
  'price': 5000000,
  'position': 'midfield-CentralMidfield',
  'club': 'RB Leipzig',
  'countries': ['Slovenia']},
 {'name': 'Dani Olmo',
  'age': 25,
  'height': 1.79,
  'price': 40000000,
  'position': 'midfield-AttackingMidfield',
  'club': 'RB Leipzig',
  'countries': ['Spain']},
 {'name': 'Dominik Szoboszlai',
  'age': 22,
  'height': 1.87,
  'price': 40000000,
  'position': 'midfield-AttackingMidfield',
  'club': 'RB Leipzig',
  'countries': ['Hungary']},
 {'name': 'Emil Forsberg',
  'age': 31,
  'height': 1.77,
  'price': 9000000,
  'position': 'midfield-AttackingMidfield',
  'club': 'RB Leipzig',
  'countries': ['Sweden']},
 {'name': 'Caden Clark',
  'age': 19,
  'height': 1.8,
  'price': 2800000,
  'position': 'midfield-AttackingMidfield',
  'club': 'RB Leipzig',
  'countries': ['United States']},
 {'name': 'Christopher Nkunku',
  'age': 25,
  'height': 1.78,
  'price': 80000000,
  'position': 'Attack-SecondStriker',
  'club': 'RB Leipzig',
  'countries': ['DR Congo', 'France']},
 {'name': 'Timo Werner',
  'age': 27,
  'height': 1.8,
  'price': 25000000,
  'position': 'Attack-Centre-Forward',
  'club': 'RB Leipzig',
  'countries': ['Germany']},
 {'name': 'André Silva',
  'age': 27,
  'height': 1.85,
  'price': 20000000,
  'position': 'Attack-Centre-Forward',
  'club': 'RB Leipzig',
  'countries': ['Portugal']},
 {'name': 'Yussuf Poulsen',
  'age': 28,
  'height': 1.92,
  'price': 10000000,
  'position': 'Attack-Centre-Forward',
  'club': 'RB Leipzig',
  'countries': ['Tanzania', 'Denmark']},
 {'name': 'Lukas Hradecky',
  'age': 33,
  'height': 1.92,
  'price': 2500000,
  'position': 'Goalkeeper',
  'club': 'B. Leverkusen',
  'countries': ['Slovakia', 'Finland']},
 {'name': 'Patrick Pentz',
  'age': 26,
  'height': 1.82,
  'price': 1500000,
  'position': 'Goalkeeper',
  'club': 'B. Leverkusen',
  'countries': ['Austria']},
 {'name': 'Andrey Lunev',
  'age': 31,
  'height': 1.9,
  'price': 1500000,
  'position': 'Goalkeeper',
  'club': 'B. Leverkusen',
  'countries': ['Russia']},
 {'name': 'Niklas Lomb',
  'age': 29,
  'height': 1.86,
  'price': 250000,
  'position': 'Goalkeeper',
  'club': 'B. Leverkusen',
  'countries': ['Germany']},
 {'name': 'Edmond Tapsoba',
  'age': 24,
  'height': 1.94,
  'price': 30000000,
  'position': 'Defender-Centre-Back',
  'club': 'B. Leverkusen',
  'countries': ['Burkina Faso']},
 {'name': 'Piero Hincapié',
  'age': 21,
  'height': 1.83,
  'price': 25000000,
  'position': 'Defender-Centre-Back',
  'club': 'B. Leverkusen',
  'countries': ['Ecuador']},
 {'name': 'Jonathan Tah',
  'age': 27,
  'height': 1.95,
  'price': 20000000,
  'position': 'Defender-Centre-Back',
  'club': 'B. Leverkusen',
  'countries': ['Germany']},
 {'name': 'Odilon Kossounou',
  'age': 22,
  'height': 1.91,
  'price': 20000000,
  'position': 'Defender-Centre-Back',
  'club': 'B. Leverkusen',
  'countries': []},
 {'name': 'Mitchel Bakker',
  'age': 22,
  'height': 1.85,
  'price': 9000000,
  'position': 'Defender-Left-Back',
  'club': 'B. Leverkusen',
  'countries': ['Netherlands']},
 {'name': 'Daley Sinkgraven',
  'age': 27,
  'height': 1.79,
  'price': 3000000,
  'position': 'Defender-Left-Back',
  'club': 'B. Leverkusen',
  'countries': ['Netherlands']},
 {'name': 'Jeremie Frimpong',
  'age': 22,
  'height': 1.71,
  'price': 35000000,
  'position': 'Defender-Right-Back',
  'club': 'B. Leverkusen',
  'countries': ['Netherlands', 'Ghana']},
 {'name': 'Timothy Fosu-Mensah',
  'age': 25,
  'height': 1.85,
  'price': 3000000,
  'position': 'Defender-Right-Back',
  'club': 'B. Leverkusen',
  'countries': ['Netherlands', 'Ghana']},
 {'name': 'Robert Andrich',
  'age': 28,
  'height': 1.87,
  'price': 11000000,
  'position': 'midfield-DefensiveMidfield',
  'club': 'B. Leverkusen',
  'countries': ['Germany']},
 {'name': 'Noah Mbamba',
  'age': 18,
  'height': 1.87,
  'price': 3000000,
  'position': 'midfield-DefensiveMidfield',
  'club': 'B. Leverkusen',
  'countries': ['Belgium']},
 {'name': 'Ayman Azhil',
  'age': 22,
  'height': 1.75,
  'price': 400000,
  'position': 'midfield-DefensiveMidfield',
  'club': 'B. Leverkusen',
  'countries': ['Germany', 'Morocco']},
 {'name': 'Joshua Eze',
  'age': 20,
  'height': 1.83,
  'price': 200000,
  'position': 'midfield-DefensiveMidfield',
  'club': 'B. Leverkusen',
  'countries': ['Germany', 'Nigeria']},
 {'name': 'Exequiel Palacios',
  'age': 24,
  'height': 1.77,
  'price': 15000000,
  'position': 'midfield-CentralMidfield',
  'club': 'B. Leverkusen',
  'countries': ['Argentina']},
 {'name': 'Kerem Demirbay',
  'age': 29,
  'height': 1.83,
  'price': 9000000,
  'position': 'midfield-CentralMidfield',
  'club': 'B. Leverkusen',
  'countries': ['Germany', 'Turkey']},
 {'name': 'Nadiem Amiri',
  'age': 26,
  'height': 1.8,
  'price': 6000000,
  'position': 'midfield-CentralMidfield',
  'club': 'B. Leverkusen',
  'countries': ['Afghanistan', 'Germany']},
 {'name': 'Florian Wirtz',
  'age': 20,
  'height': 1.76,
  'price': 85000000,
  'position': 'midfield-AttackingMidfield',
  'club': 'B. Leverkusen',
  'countries': ['Germany']},
 {'name': 'Callum Hudson-Odoi',
  'age': 22,
  'height': 1.77,
  'price': 17000000,
  'position': 'Attack-LeftWinger',
  'club': 'B. Leverkusen',
  'countries': ['England', 'Ghana']},
 {'name': 'Amine Adli',
  'age': 23,
  'height': 1.74,
  'price': 15000000,
  'position': 'Attack-LeftWinger',
  'club': 'B. Leverkusen',
  'countries': ['Morocco', 'France']},
 {'name': 'Moussa Diaby',
  'age': 23,
  'height': 1.7,
  'price': 50000000,
  'position': 'Attack-RightWinger',
  'club': 'B. Leverkusen',
  'countries': ['France', 'Mali']},
 {'name': 'Karim Bellarabi',
  'age': 33,
  'height': 1.84,
  'price': 2500000,
  'position': 'Attack-RightWinger',
  'club': 'B. Leverkusen',
  'countries': ['Germany', 'Morocco']},
 {'name': 'Patrik Schick',
  'age': 27,
  'height': 1.91,
  'price': 30000000,
  'position': 'Attack-Centre-Forward',
  'club': 'B. Leverkusen',
  'countries': ['Czech Republic']},
 {'name': 'Adam Hlozek',
  'age': 20,
  'height': 1.88,
  'price': 15000000,
  'position': 'Attack-Centre-Forward',
  'club': 'B. Leverkusen',
  'countries': ['Czech Republic']},
 {'name': 'Sardar Azmoun',
  'age': 28,
  'height': 1.86,
  'price': 12000000,
  'position': 'Attack-Centre-Forward',
  'club': 'B. Leverkusen',
  'countries': ['Iran']},

In [36]:
from pymongo import MongoClient

client = MongoClient("mongodb://admin:123@localhost:27017/?authSource=admin")
db = client["bundesliga"]
collection = db["players"]

In [84]:
# import time

# start = time.perf_counter()

# batch_size = 250

# for i in range(0, len(records), batch_size):
#     batch = records[i:i + batch_size]
#     collection.insert_many(batch)
#     print(f"Inserted {i // batch_size + 1}.batch with {len(batch)} records.")

# end = time.perf_counter()
# time_taken = end - start
# print(f"Taken time is : {time_taken * 1000:.2f} ms or {time_taken} s")

In [61]:
# collection.delete_many({})

In [62]:
# start = time.perf_counter()
# for i in range(0, len(records)):
#     try:
#         collection.insert_one(records[i])
#     except Exception as e:
#         continue
# print('OK')
# print(f"Inserted {len(records)} records.")
# end = time.perf_counter()
# time_taken = end - start
# print(f"Taken time is : {time_taken * 1000:.2f} ms or {time_taken} s")

In [63]:
start = time.perf_counter()

results = list(collection.find())

end = time.perf_counter()

time_taken = end - start
print(f"Query Time: {time_taken * 1000:.2f} ms")
print(f"Documents fetched: {len(results)}")

Query Time: 3.92 ms
Documents fetched: 506

In [64]:
results

[{'_id': ObjectId('69d901747943dd8b5d62cf1b'),
  'name': 'Manuel Neuer',
  'age': 37,
  'height': 1.93,
  'price': 7000000,
  'position': 'Goalkeeper',
  'club': 'Bayern Munich',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cf1c'),
  'name': 'Yann Sommer',
  'age': 34,
  'height': 1.83,
  'price': 5000000,
  'position': 'Goalkeeper',
  'club': 'Bayern Munich',
  'countries': ['Switzerland']},
 {'_id': ObjectId('69d901747943dd8b5d62cf1d'),
  'name': 'Sven Ulreich',
  'age': 34,
  'height': 1.92,
  'price': 900000,
  'position': 'Goalkeeper',
  'club': 'Bayern Munich',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cf1e'),
  'name': 'Johannes Schenk',
  'age': 20,
  'height': 1.91,
  'price': 300000,
  'position': 'Goalkeeper',
  'club': 'Bayern Munich',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cf1f'),
  'name': 'Matthijs de Ligt',
  'age': 23,
  'height': 1.89,
  'price': 75000000,
  'position': 'Defender-Centre-Back',
  'club': 'Bayern Munich',
  'countries': ['Netherlands']},
 {'_id': ObjectId('69d901747943dd8b5d62cf20'),
  'name': 'Dayot Upamecano',
  'age': 24,
  'height': 1.86,
  'price': 60000000,
  'position': 'Defender-Centre-Back',
  'club': 'Bayern Munich',
  'countries': ['Guinea-Bissau', 'France']},
 {'_id': ObjectId('69d901747943dd8b5d62cf21'),
  'name': 'Lucas Hernández',
  'age': 27,
  'height': 1.84,
  'price': 50000000,
  'position': 'Defender-Centre-Back',
  'club': 'Bayern Munich',
  'countries': ['France', 'Spain']},
 {'_id': ObjectId('69d901747943dd8b5d62cf22'),
  'name': 'Alphonso Davies',
  'age': 22,
  'height': 1.85,
  'price': 70000000,
  'position': 'Defender-Left-Back',
  'club': 'Bayern Munich',
  'countries': ['Liberia', 'Canada']},
 {'_id': ObjectId('69d901747943dd8b5d62cf23'),
  'name': 'Daley Blind',
  'age': 33,
  'height': 1.8,
  'price': 6000000,
  'position': 'Defender-Left-Back',
  'club': 'Bayern Munich',
  'countries': ['Netherlands']},
 {'_id': ObjectId('69d901747943dd8b5d62cf24'),
  'name': 'João Cancelo',
  'age': 28,
  'height': 1.82,
  'price': 60000000,
  'position': 'Defender-Right-Back',
  'club': 'Bayern Munich',
  'countries': ['Portugal']},
 {'_id': ObjectId('69d901747943dd8b5d62cf25'),
  'name': 'Benjamin Pavard',
  'age': 27,
  'height': 1.86,
  'price': 35000000,
  'position': 'Defender-Right-Back',
  'club': 'Bayern Munich',
  'countries': ['France']},
 {'_id': ObjectId('69d901747943dd8b5d62cf26'),
  'name': 'Noussair Mazraoui',
  'age': 25,
  'height': 1.83,
  'price': 28000000,
  'position': 'Defender-Right-Back',
  'club': 'Bayern Munich',
  'countries': ['Netherlands', 'Morocco']},
 {'_id': ObjectId('69d901747943dd8b5d62cf27'),
  'name': 'Josip Stanisic',
  'age': 23,
  'height': 1.87,
  'price': 12000000,
  'position': 'Defender-Right-Back',
  'club': 'Bayern Munich',
  'countries': ['Croatia', 'Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cf28'),
  'name': 'Bouna Sarr',
  'age': 31,
  'height': 1.77,
  'price': 2500000,
  'position': 'Defender-Right-Back',
  'club': 'Bayern Munich',
  'countries': ['Senegal', 'France']},
 {'_id': ObjectId('69d901747943dd8b5d62cf29'),
  'name': 'Joshua Kimmich',
  'age': 28,
  'height': 1.77,
  'price': 80000000,
  'position': 'midfield-DefensiveMidfield',
  'club': 'Bayern Munich',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cf2a'),
  'name': 'Leon Goretzka',
  'age': 28,
  'height': 1.89,
  'price': 65000000,
  'position': 'midfield-CentralMidfield',
  'club': 'Bayern Munich',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cf2b'),
  'name': 'Ryan Gravenberch',
  'age': 20,
  'height': 1.9,
  'price': 30000000,
  'position': 'midfield-CentralMidfield',
  'club': 'Bayern Munich',
  'countries': ['Netherlands', 'Suriname']},
 {'_id': ObjectId('69d901747943dd8b5d62cf2c'),
  'name': 'Jamal Musiala',
  'age': 20,
  'height': 1.84,
  'price': 110000000,
  'position': 'midfield-AttackingMidfield',
  'club': 'Bayern Munich',
  'countries': ['England', 'Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cf2d'),
  'name': 'Paul Wanner',
  'age': 17,
  'height': 1.85,
  'price': 3000000,
  'position': 'midfield-AttackingMidfield',
  'club': 'Bayern Munich',
  'countries': ['Austria', 'Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cf2e'),
  'name': 'Arijon Ibrahimovic',
  'age': 17,
  'height': 1.76,
  'price': 1000000,
  'position': 'midfield-AttackingMidfield',
  'club': 'Bayern Munich',
  'countries': ['Germany', 'Kosovo']},
 {'_id': ObjectId('69d901747943dd8b5d62cf2f'),
  'name': 'Kingsley Coman',
  'age': 26,
  'height': 1.81,
  'price': 65000000,
  'position': 'Attack-LeftWinger',
  'club': 'Bayern Munich',
  'countries': ['Guadeloupe', 'France']},
 {'_id': ObjectId('69d901747943dd8b5d62cf30'),
  'name': 'Sadio Mané',
  'age': 31,
  'height': 1.74,
  'price': 45000000,
  'position': 'Attack-LeftWinger',
  'club': 'Bayern Munich',
  'countries': ['Senegal']},
 {'_id': ObjectId('69d901747943dd8b5d62cf31'),
  'name': 'Leroy Sané',
  'age': 27,
  'height': 1.83,
  'price': 70000000,
  'position': 'Attack-RightWinger',
  'club': 'Bayern Munich',
  'countries': ['Germany', 'France']},
 {'_id': ObjectId('69d901747943dd8b5d62cf32'),
  'name': 'Serge Gnabry',
  'age': 27,
  'height': 1.76,
  'price': 55000000,
  'position': 'Attack-RightWinger',
  'club': 'Bayern Munich',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cf33'),
  'name': 'Thomas Müller',
  'age': 33,
  'height': 1.85,
  'price': 18000000,
  'position': 'Attack-SecondStriker',
  'club': 'Bayern Munich',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cf34'),
  'name': 'Mathys Tel',
  'age': 18,
  'height': 1.83,
  'price': 20000000,
  'position': 'Attack-Centre-Forward',
  'club': 'Bayern Munich',
  'countries': ['Guadeloupe', 'France']},
 {'_id': ObjectId('69d901747943dd8b5d62cf35'),
  'name': 'Eric Maxim Choupo-Moting',
  'age': 34,
  'height': 1.91,
  'price': 6000000,
  'position': 'Attack-Centre-Forward',
  'club': 'Bayern Munich',
  'countries': ['Cameroon', 'Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cf36'),
  'name': 'Gregor Kobel',
  'age': 25,
  'height': 1.94,
  'price': 35000000,
  'position': 'Goalkeeper',
  'club': 'Bor. Dortmund',
  'countries': ['Switzerland']},
 {'_id': ObjectId('69d901747943dd8b5d62cf37'),
  'name': 'Marcel Lotka',
  'age': 21,
  'height': 1.9,
  'price': 1300000,
  'position': 'Goalkeeper',
  'club': 'Bor. Dortmund',
  'countries': ['Germany', 'Poland']},
 {'_id': ObjectId('69d901747943dd8b5d62cf38'),
  'name': 'Alexander Meyer',
  'age': 32,
  'height': 1.95,
  'price': 1000000,
  'position': 'Goalkeeper',
  'club': 'Bor. Dortmund',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cf39'),
  'name': 'Luca Unbehaun',
  'age': 22,
  'height': 1.85,
  'price': 1000000,
  'position': 'Goalkeeper',
  'club': 'Bor. Dortmund',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cf3a'),
  'name': 'Nico Schlotterbeck',
  'age': 23,
  'height': 1.91,
  'price': 40000000,
  'position': 'Defender-Centre-Back',
  'club': 'Bor. Dortmund',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cf3b'),
  'name': 'Niklas Süle',
  'age': 27,
  'height': 1.95,
  'price': 35000000,
  'position': 'Defender-Centre-Back',
  'club': 'Bor. Dortmund',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cf3c'),
  'name': 'Mats Hummels',
  'age': 34,
  'height': 1.91,
  'price': 6500000,
  'position': 'Defender-Centre-Back',
  'club': 'Bor. Dortmund',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cf3d'),
  'name': 'Soumaïla Coulibaly',
  'age': 19,
  'height': 1.9,
  'price': 1000000,
  'position': 'Defender-Centre-Back',
  'club': 'Bor. Dortmund',
  'countries': ['France', 'Mali']},
 {'_id': ObjectId('69d901747943dd8b5d62cf3e'),
  'name': 'Antonios Papadopoulos',
  'age': 23,
  'height': 1.86,
  'price': 600000,
  'position': 'Defender-Centre-Back',
  'club': 'B. Dortmund II',
  'countries': ['Germany', 'Greece']},
 {'_id': ObjectId('69d901747943dd8b5d62cf3f'),
  'name': 'Raphaël Guerreiro',
  'age': 29,
  'height': 1.7,
  'price': 20000000,
  'position': 'Defender-Left-Back',
  'club': 'Bor. Dortmund',
  'countries': ['Portugal', 'France']},
 {'_id': ObjectId('69d901747943dd8b5d62cf40'),
  'name': 'Tom Rothe',
  'age': 18,
  'height': 1.93,
  'price': 3500000,
  'position': 'Defender-Left-Back',
  'club': 'Bor. Dortmund',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cf41'),
  'name': 'Nico Schulz',
  'age': 30,
  'height': 1.8,
  'price': 2000000,
  'position': 'Defender-Left-Back',
  'club': 'Bor. Dortmund',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cf42'),
  'name': 'Julian Ryerson',
  'age': 25,
  'height': 1.83,
  'price': 10000000,
  'position': 'Defender-Right-Back',
  'club': 'Bor. Dortmund',
  'countries': ['Norway']},
 {'_id': ObjectId('69d901747943dd8b5d62cf43'),
  'name': 'Marius Wolf',
  'age': 27,
  'height': 1.87,
  'price': 9000000,
  'position': 'Defender-Right-Back',
  'club': 'Bor. Dortmund',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cf44'),
  'name': 'Thomas Meunier',
  'age': 31,
  'height': 1.91,
  'price': 6500000,
  'position': 'Defender-Right-Back',
  'club': 'Bor. Dortmund',
  'countries': ['Belgium']},
 {'_id': ObjectId('69d901747943dd8b5d62cf45'),
  'name': 'Mateu Morey Bauzà',
  'age': 23,
  'height': 1.73,
  'price': 1500000,
  'position': 'Defender-Right-Back',
  'club': 'Bor. Dortmund',
  'countries': ['Spain']},
 {'_id': ObjectId('69d901747943dd8b5d62cf46'),
  'name': 'Felix Passlack',
  'age': 24,
  'height': 1.7,
  'price': 1500000,
  'position': 'Defender-Right-Back',
  'club': 'Bor. Dortmund',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cf47'),
  'name': 'Salih Özcan',
  'age': 25,
  'height': 1.83,
  'price': 17000000,
  'position': 'midfield-DefensiveMidfield',
  'club': 'Bor. Dortmund',
  'countries': ['Germany', 'Turkey']},
 {'_id': ObjectId('69d901747943dd8b5d62cf48'),
  'name': 'Emre Can',
  'age': 29,
  'height': 1.86,
  'price': 14000000,
  'position': 'midfield-DefensiveMidfield',
  'club': 'Bor. Dortmund',
  'countries': ['Germany', 'Turkey']},
 {'_id': ObjectId('69d901747943dd8b5d62cf49'),
  'name': 'Abdoulaye Kamara',
  'age': 18,
  'height': 1.83,
  'price': 1000000,
  'position': 'midfield-DefensiveMidfield',
  'club': 'B. Dortmund II',
  'countries': ['France', 'Guinea']},
 {'_id': ObjectId('69d901747943dd8b5d62cf4a'),
  'name': 'Jude Bellingham',
  'age': 19,
  'height': 1.86,
  'price': 120000000,
  'position': 'midfield-CentralMidfield',
  'club': 'Bor. Dortmund',
  'countries': ['England']},
 {'_id': ObjectId('69d901747943dd8b5d62cf4b'),
  'name': 'Mahmoud Dahoud',
  'age': 27,
  'height': 1.78,
  'price': 12000000,
  'position': 'midfield-CentralMidfield',
  'club': 'Bor. Dortmund',
  'countries': ['Germany', 'Syria']},
 {'_id': ObjectId('69d901747943dd8b5d62cf4c'),
  'name': 'Julian Brandt',
  'age': 27,
  'height': 1.85,
  'price': 40000000,
  'position': 'midfield-AttackingMidfield',
  'club': 'Bor. Dortmund',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cf4d'),
  'name': 'Giovanni Reyna',
  'age': 20,
  'height': 1.85,
  'price': 28000000,
  'position': 'midfield-AttackingMidfield',
  'club': 'Bor. Dortmund',
  'countries': ['United States', 'Portugal']},
 {'_id': ObjectId('69d901747943dd8b5d62cf4e'),
  'name': 'Marco Reus',
  'age': 33,
  'height': 1.8,
  'price': 9000000,
  'position': 'midfield-AttackingMidfield',
  'club': 'Bor. Dortmund',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cf4f'),
  'name': 'Göktan Gürpüz',
  'age': 20,
  'height': 1.76,
  'price': 300000,
  'position': 'midfield-AttackingMidfield',
  'club': 'B. Dortmund II',
  'countries': ['Germany', 'Turkey']},
 {'_id': ObjectId('69d901747943dd8b5d62cf50'),
  'name': 'Karim Adeyemi',
  'age': 21,
  'height': 1.8,
  'price': 35000000,
  'position': 'Attack-LeftWinger',
  'club': 'Bor. Dortmund',
  'countries': ['Germany', 'Nigeria']},
 {'_id': ObjectId('69d901747943dd8b5d62cf51'),
  'name': 'Jamie Bynoe-Gittens',
  'age': 18,
  'height': 1.77,
  'price': 14000000,
  'position': 'Attack-LeftWinger',
  'club': 'Bor. Dortmund',
  'countries': ['Barbados', 'England']},
 {'_id': ObjectId('69d901747943dd8b5d62cf52'),
  'name': 'Donyell Malen',
  'age': 24,
  'height': 1.78,
  'price': 16000000,
  'position': 'Attack-RightWinger',
  'club': 'Bor. Dortmund',
  'countries': ['Netherlands', 'Suriname']},
 {'_id': ObjectId('69d901747943dd8b5d62cf53'),
  'name': 'Julien Duranville',
  'age': 17,
  'height': 1.7,
  'price': 5000000,
  'position': 'Attack-RightWinger',
  'club': 'Bor. Dortmund',
  'countries': ['Belgium']},
 {'_id': ObjectId('69d901747943dd8b5d62cf54'),
  'name': 'Sébastien Haller',
  'age': 28,
  'height': 1.91,
  'price': 30000000,
  'position': 'Attack-Centre-Forward',
  'club': 'Bor. Dortmund',
  'countries': ['France']},
 {'_id': ObjectId('69d901747943dd8b5d62cf55'),
  'name': 'Youssoufa Moukoko',
  'age': 18,
  'height': 1.79,
  'price': 30000000,
  'position': 'Attack-Centre-Forward',
  'club': 'Bor. Dortmund',
  'countries': ['Cameroon', 'Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cf56'),
  'name': 'Anthony Modeste',
  'age': 35,
  'height': 1.88,
  'price': 1000000,
  'position': 'Attack-Centre-Forward',
  'club': 'Bor. Dortmund',
  'countries': ['Martinique', 'France']},
 {'_id': ObjectId('69d901747943dd8b5d62cf57'),
  'name': 'Péter Gulácsi',
  'age': 33,
  'height': 1.9,
  'price': 6000000,
  'position': 'Goalkeeper',
  'club': 'RB Leipzig',
  'countries': ['Hungary']},
 {'_id': ObjectId('69d901747943dd8b5d62cf58'),
  'name': 'Janis Blaswich',
  'age': 32,
  'height': 1.93,
  'price': 2000000,
  'position': 'Goalkeeper',
  'club': 'RB Leipzig',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cf59'),
  'name': 'Örjan Nyland',
  'age': 32,
  'height': 1.92,
  'price': 600000,
  'position': 'Goalkeeper',
  'club': 'RB Leipzig',
  'countries': ['Norway']},
 {'_id': ObjectId('69d901747943dd8b5d62cf5a'),
  'name': 'Jonas Nickisch',
  'age': 18,
  'height': 1.9,
  'price': 200000,
  'position': 'Goalkeeper',
  'club': 'RB Leipzig U19',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cf5b'),
  'name': 'Timo Schlieck',
  'age': 17,
  'height': 1.95,
  'price': 200000,
  'position': 'Goalkeeper',
  'club': 'RB Leipzig U17',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cf5c'),
  'name': 'Josko Gvardiol',
  'age': 21,
  'height': 1.85,
  'price': 75000000,
  'position': 'Defender-Centre-Back',
  'club': 'RB Leipzig',
  'countries': ['Croatia']},
 {'_id': ObjectId('69d901747943dd8b5d62cf5d'),
  'name': 'Mohamed Simakan',
  'age': 23,
  'height': 1.87,
  'price': 28000000,
  'position': 'Defender-Centre-Back',
  'club': 'RB Leipzig',
  'countries': ['France', 'Guinea']},
 {'_id': ObjectId('69d901747943dd8b5d62cf5e'),
  'name': 'Abdou Diallo',
  'age': 27,
  'height': 1.87,
  'price': 15000000,
  'position': 'Defender-Centre-Back',
  'club': 'RB Leipzig',
  'countries': ['Senegal', 'France']},
 {'_id': ObjectId('69d901747943dd8b5d62cf5f'),
  'name': 'Willi Orbán',
  'age': 30,
  'height': 1.86,
  'price': 10000000,
  'position': 'Defender-Centre-Back',
  'club': 'RB Leipzig',
  'countries': ['Germany', 'Hungary']},
 {'_id': ObjectId('69d901747943dd8b5d62cf60'),
  'name': 'David Raum',
  'age': 25,
  'height': 1.8,
  'price': 20000000,
  'position': 'Defender-Left-Back',
  'club': 'RB Leipzig',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cf61'),
  'name': 'Marcel Halstenberg',
  'age': 31,
  'height': 1.88,
  'price': 4000000,
  'position': 'Defender-Left-Back',
  'club': 'RB Leipzig',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cf62'),
  'name': 'Sanoussy Ba',
  'age': 19,
  'height': 1.84,
  'price': 500000,
  'position': 'Defender-Left-Back',
  'club': 'RB Leipzig',
  'countries': ['Germany', 'Senegal']},
 {'_id': ObjectId('69d901747943dd8b5d62cf63'),
  'name': 'Benjamin Henrichs',
  'age': 26,
  'height': 1.85,
  'price': 15000000,
  'position': 'Defender-Right-Back',
  'club': 'RB Leipzig',
  'countries': ['Germany', 'Ghana']},
 {'_id': ObjectId('69d901747943dd8b5d62cf64'),
  'name': 'Lukas Klostermann',
  'age': 26,
  'height': 1.89,
  'price': 12000000,
  'position': 'Defender-Right-Back',
  'club': 'RB Leipzig',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cf65'),
  'name': 'Konrad Laimer',
  'age': 25,
  'height': 1.8,
  'price': 28000000,
  'position': 'midfield-CentralMidfield',
  'club': 'RB Leipzig',
  'countries': ['Austria']},
 {'_id': ObjectId('69d901747943dd8b5d62cf66'),
  'name': 'Xaver Schlager',
  'age': 25,
  'height': 1.74,
  'price': 22000000,
  'position': 'midfield-CentralMidfield',
  'club': 'RB Leipzig',
  'countries': ['Austria']},
 {'_id': ObjectId('69d901747943dd8b5d62cf67'),
  'name': 'Amadou Haidara',
  'age': 25,
  'height': 1.75,
  'price': 17000000,
  'position': 'midfield-CentralMidfield',
  'club': 'RB Leipzig',
  'countries': ['Mali']},
 {'_id': ObjectId('69d901747943dd8b5d62cf68'),
  'name': 'Kevin Kampl',
  'age': 32,
  'height': 1.78,
  'price': 5000000,
  'position': 'midfield-CentralMidfield',
  'club': 'RB Leipzig',
  'countries': ['Slovenia']},
 {'_id': ObjectId('69d901747943dd8b5d62cf69'),
  'name': 'Dani Olmo',
  'age': 25,
  'height': 1.79,
  'price': 40000000,
  'position': 'midfield-AttackingMidfield',
  'club': 'RB Leipzig',
  'countries': ['Spain']},
 {'_id': ObjectId('69d901747943dd8b5d62cf6a'),
  'name': 'Dominik Szoboszlai',
  'age': 22,
  'height': 1.87,
  'price': 40000000,
  'position': 'midfield-AttackingMidfield',
  'club': 'RB Leipzig',
  'countries': ['Hungary']},
 {'_id': ObjectId('69d901747943dd8b5d62cf6b'),
  'name': 'Emil Forsberg',
  'age': 31,
  'height': 1.77,
  'price': 9000000,
  'position': 'midfield-AttackingMidfield',
  'club': 'RB Leipzig',
  'countries': ['Sweden']},
 {'_id': ObjectId('69d901747943dd8b5d62cf6c'),
  'name': 'Caden Clark',
  'age': 19,
  'height': 1.8,
  'price': 2800000,
  'position': 'midfield-AttackingMidfield',
  'club': 'RB Leipzig',
  'countries': ['United States']},
 {'_id': ObjectId('69d901747943dd8b5d62cf6d'),
  'name': 'Christopher Nkunku',
  'age': 25,
  'height': 1.78,
  'price': 80000000,
  'position': 'Attack-SecondStriker',
  'club': 'RB Leipzig',
  'countries': ['DR Congo', 'France']},
 {'_id': ObjectId('69d901747943dd8b5d62cf6e'),
  'name': 'Timo Werner',
  'age': 27,
  'height': 1.8,
  'price': 25000000,
  'position': 'Attack-Centre-Forward',
  'club': 'RB Leipzig',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cf6f'),
  'name': 'André Silva',
  'age': 27,
  'height': 1.85,
  'price': 20000000,
  'position': 'Attack-Centre-Forward',
  'club': 'RB Leipzig',
  'countries': ['Portugal']},
 {'_id': ObjectId('69d901747943dd8b5d62cf70'),
  'name': 'Yussuf Poulsen',
  'age': 28,
  'height': 1.92,
  'price': 10000000,
  'position': 'Attack-Centre-Forward',
  'club': 'RB Leipzig',
  'countries': ['Tanzania', 'Denmark']},
 {'_id': ObjectId('69d901747943dd8b5d62cf71'),
  'name': 'Lukas Hradecky',
  'age': 33,
  'height': 1.92,
  'price': 2500000,
  'position': 'Goalkeeper',
  'club': 'B. Leverkusen',
  'countries': ['Slovakia', 'Finland']},
 {'_id': ObjectId('69d901747943dd8b5d62cf72'),
  'name': 'Patrick Pentz',
  'age': 26,
  'height': 1.82,
  'price': 1500000,
  'position': 'Goalkeeper',
  'club': 'B. Leverkusen',
  'countries': ['Austria']},
 {'_id': ObjectId('69d901747943dd8b5d62cf73'),
  'name': 'Andrey Lunev',
  'age': 31,
  'height': 1.9,
  'price': 1500000,
  'position': 'Goalkeeper',
  'club': 'B. Leverkusen',
  'countries': ['Russia']},
 {'_id': ObjectId('69d901747943dd8b5d62cf74'),
  'name': 'Niklas Lomb',
  'age': 29,
  'height': 1.86,
  'price': 250000,

In [65]:
len(list(collection.find({"height" : {"$lt" : 1.90}})))

385

In [66]:
len(list(collection.find({"age" : {"$gt" : 35}})))

9

In [67]:
results = list(collection.find({"nationality": "Germany"}).sort("age", 1).limit(10))

results

[]

In [68]:
list(collection.find({"age": {"$gt": 27}}))

[{'_id': ObjectId('69d901747943dd8b5d62cf1b'),
  'name': 'Manuel Neuer',
  'age': 37,
  'height': 1.93,
  'price': 7000000,
  'position': 'Goalkeeper',
  'club': 'Bayern Munich',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cf1c'),
  'name': 'Yann Sommer',
  'age': 34,
  'height': 1.83,
  'price': 5000000,
  'position': 'Goalkeeper',
  'club': 'Bayern Munich',
  'countries': ['Switzerland']},
 {'_id': ObjectId('69d901747943dd8b5d62cf1d'),
  'name': 'Sven Ulreich',
  'age': 34,
  'height': 1.92,
  'price': 900000,
  'position': 'Goalkeeper',
  'club': 'Bayern Munich',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cf23'),
  'name': 'Daley Blind',
  'age': 33,
  'height': 1.8,
  'price': 6000000,
  'position': 'Defender-Left-Back',
  'club': 'Bayern Munich',
  'countries': ['Netherlands']},
 {'_id': ObjectId('69d901747943dd8b5d62cf24'),
  'name': 'João Cancelo',
  'age': 28,
  'height': 1.82,
  'price': 60000000,
  'position': 'Defender-Right-Back',
  'club': 'Bayern Munich',
  'countries': ['Portugal']},
 {'_id': ObjectId('69d901747943dd8b5d62cf28'),
  'name': 'Bouna Sarr',
  'age': 31,
  'height': 1.77,
  'price': 2500000,
  'position': 'Defender-Right-Back',
  'club': 'Bayern Munich',
  'countries': ['Senegal', 'France']},
 {'_id': ObjectId('69d901747943dd8b5d62cf29'),
  'name': 'Joshua Kimmich',
  'age': 28,
  'height': 1.77,
  'price': 80000000,
  'position': 'midfield-DefensiveMidfield',
  'club': 'Bayern Munich',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cf2a'),
  'name': 'Leon Goretzka',
  'age': 28,
  'height': 1.89,
  'price': 65000000,
  'position': 'midfield-CentralMidfield',
  'club': 'Bayern Munich',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cf30'),
  'name': 'Sadio Mané',
  'age': 31,
  'height': 1.74,
  'price': 45000000,
  'position': 'Attack-LeftWinger',
  'club': 'Bayern Munich',
  'countries': ['Senegal']},
 {'_id': ObjectId('69d901747943dd8b5d62cf33'),
  'name': 'Thomas Müller',
  'age': 33,
  'height': 1.85,
  'price': 18000000,
  'position': 'Attack-SecondStriker',
  'club': 'Bayern Munich',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cf35'),
  'name': 'Eric Maxim Choupo-Moting',
  'age': 34,
  'height': 1.91,
  'price': 6000000,
  'position': 'Attack-Centre-Forward',
  'club': 'Bayern Munich',
  'countries': ['Cameroon', 'Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cf38'),
  'name': 'Alexander Meyer',
  'age': 32,
  'height': 1.95,
  'price': 1000000,
  'position': 'Goalkeeper',
  'club': 'Bor. Dortmund',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cf3c'),
  'name': 'Mats Hummels',
  'age': 34,
  'height': 1.91,
  'price': 6500000,
  'position': 'Defender-Centre-Back',
  'club': 'Bor. Dortmund',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cf3f'),
  'name': 'Raphaël Guerreiro',
  'age': 29,
  'height': 1.7,
  'price': 20000000,
  'position': 'Defender-Left-Back',
  'club': 'Bor. Dortmund',
  'countries': ['Portugal', 'France']},
 {'_id': ObjectId('69d901747943dd8b5d62cf41'),
  'name': 'Nico Schulz',
  'age': 30,
  'height': 1.8,
  'price': 2000000,
  'position': 'Defender-Left-Back',
  'club': 'Bor. Dortmund',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cf44'),
  'name': 'Thomas Meunier',
  'age': 31,
  'height': 1.91,
  'price': 6500000,
  'position': 'Defender-Right-Back',
  'club': 'Bor. Dortmund',
  'countries': ['Belgium']},
 {'_id': ObjectId('69d901747943dd8b5d62cf48'),
  'name': 'Emre Can',
  'age': 29,
  'height': 1.86,
  'price': 14000000,
  'position': 'midfield-DefensiveMidfield',
  'club': 'Bor. Dortmund',
  'countries': ['Germany', 'Turkey']},
 {'_id': ObjectId('69d901747943dd8b5d62cf4e'),
  'name': 'Marco Reus',
  'age': 33,
  'height': 1.8,
  'price': 9000000,
  'position': 'midfield-AttackingMidfield',
  'club': 'Bor. Dortmund',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cf54'),
  'name': 'Sébastien Haller',
  'age': 28,
  'height': 1.91,
  'price': 30000000,
  'position': 'Attack-Centre-Forward',
  'club': 'Bor. Dortmund',
  'countries': ['France']},
 {'_id': ObjectId('69d901747943dd8b5d62cf56'),
  'name': 'Anthony Modeste',
  'age': 35,
  'height': 1.88,
  'price': 1000000,
  'position': 'Attack-Centre-Forward',
  'club': 'Bor. Dortmund',
  'countries': ['Martinique', 'France']},
 {'_id': ObjectId('69d901747943dd8b5d62cf57'),
  'name': 'Péter Gulácsi',
  'age': 33,
  'height': 1.9,
  'price': 6000000,
  'position': 'Goalkeeper',
  'club': 'RB Leipzig',
  'countries': ['Hungary']},
 {'_id': ObjectId('69d901747943dd8b5d62cf58'),
  'name': 'Janis Blaswich',
  'age': 32,
  'height': 1.93,
  'price': 2000000,
  'position': 'Goalkeeper',
  'club': 'RB Leipzig',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cf59'),
  'name': 'Örjan Nyland',
  'age': 32,
  'height': 1.92,
  'price': 600000,
  'position': 'Goalkeeper',
  'club': 'RB Leipzig',
  'countries': ['Norway']},
 {'_id': ObjectId('69d901747943dd8b5d62cf5f'),
  'name': 'Willi Orbán',
  'age': 30,
  'height': 1.86,
  'price': 10000000,
  'position': 'Defender-Centre-Back',
  'club': 'RB Leipzig',
  'countries': ['Germany', 'Hungary']},
 {'_id': ObjectId('69d901747943dd8b5d62cf61'),
  'name': 'Marcel Halstenberg',
  'age': 31,
  'height': 1.88,
  'price': 4000000,
  'position': 'Defender-Left-Back',
  'club': 'RB Leipzig',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cf68'),
  'name': 'Kevin Kampl',
  'age': 32,
  'height': 1.78,
  'price': 5000000,
  'position': 'midfield-CentralMidfield',
  'club': 'RB Leipzig',
  'countries': ['Slovenia']},
 {'_id': ObjectId('69d901747943dd8b5d62cf6b'),
  'name': 'Emil Forsberg',
  'age': 31,
  'height': 1.77,
  'price': 9000000,
  'position': 'midfield-AttackingMidfield',
  'club': 'RB Leipzig',
  'countries': ['Sweden']},
 {'_id': ObjectId('69d901747943dd8b5d62cf70'),
  'name': 'Yussuf Poulsen',
  'age': 28,
  'height': 1.92,
  'price': 10000000,
  'position': 'Attack-Centre-Forward',
  'club': 'RB Leipzig',
  'countries': ['Tanzania', 'Denmark']},
 {'_id': ObjectId('69d901747943dd8b5d62cf71'),
  'name': 'Lukas Hradecky',
  'age': 33,
  'height': 1.92,
  'price': 2500000,
  'position': 'Goalkeeper',
  'club': 'B. Leverkusen',
  'countries': ['Slovakia', 'Finland']},
 {'_id': ObjectId('69d901747943dd8b5d62cf73'),
  'name': 'Andrey Lunev',
  'age': 31,
  'height': 1.9,
  'price': 1500000,
  'position': 'Goalkeeper',
  'club': 'B. Leverkusen',
  'countries': ['Russia']},
 {'_id': ObjectId('69d901747943dd8b5d62cf74'),
  'name': 'Niklas Lomb',
  'age': 29,
  'height': 1.86,
  'price': 250000,
  'position': 'Goalkeeper',
  'club': 'B. Leverkusen',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cf7d'),
  'name': 'Robert Andrich',
  'age': 28,
  'height': 1.87,
  'price': 11000000,
  'position': 'midfield-DefensiveMidfield',
  'club': 'B. Leverkusen',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cf82'),
  'name': 'Kerem Demirbay',
  'age': 29,
  'height': 1.83,
  'price': 9000000,
  'position': 'midfield-CentralMidfield',
  'club': 'B. Leverkusen',
  'countries': ['Germany', 'Turkey']},
 {'_id': ObjectId('69d901747943dd8b5d62cf88'),
  'name': 'Karim Bellarabi',
  'age': 33,
  'height': 1.84,
  'price': 2500000,
  'position': 'Attack-RightWinger',
  'club': 'B. Leverkusen',
  'countries': ['Germany', 'Morocco']},
 {'_id': ObjectId('69d901747943dd8b5d62cf8b'),
  'name': 'Sardar Azmoun',
  'age': 28,
  'height': 1.86,
  'price': 12000000,
  'position': 'Attack-Centre-Forward',
  'club': 'B. Leverkusen',
  'countries': ['Iran']},
 {'_id': ObjectId('69d901747943dd8b5d62cf8c'),
  'name': 'Kevin Trapp',
  'age': 32,
  'height': 1.89,
  'price': 8500000,
  'position': 'Goalkeeper',
  'club': 'E. Frankfurt',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cf8e'),
  'name': 'Jens Grahl',
  'age': 34,
  'height': 1.92,
  'price': 200000,
  'position': 'Goalkeeper',
  'club': 'E. Frankfurt',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cf94'),
  'name': 'Makoto Hasebe',
  'age': 39,
  'height': 1.8,
  'price': 800000,
  'position': 'Defender-Centre-Back',
  'club': 'E. Frankfurt',
  'countries': ['Japan']},
 {'_id': ObjectId('69d901747943dd8b5d62cf95'),
  'name': 'Philipp Max',
  'age': 29,
  'height': 1.77,
  'price': 6000000,
  'position': 'Defender-Left-Back',
  'club': 'E. Frankfurt',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cf96'),
  'name': 'Christopher Lenz',
  'age': 28,
  'height': 1.8,
  'price': 5000000,
  'position': 'Defender-Left-Back',
  'club': 'E. Frankfurt',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cf98'),
  'name': 'Timothy Chandler',
  'age': 33,
  'height': 1.86,
  'price': 1200000,
  'position': 'Defender-Right-Back',
  'club': 'E. Frankfurt',
  'countries': ['United States', 'Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cf9b'),
  'name': 'Sebastian Rode',
  'age': 32,
  'height': 1.79,
  'price': 2500000,
  'position': 'midfield-CentralMidfield',
  'club': 'E. Frankfurt',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cfa1'),
  'name': 'Mario Götze',
  'age': 30,
  'height': 1.76,
  'price': 13000000,
  'position': 'midfield-AttackingMidfield',
  'club': 'E. Frankfurt',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cfa7'),
  'name': 'Lucas Alario',
  'age': 30,
  'height': 1.85,
  'price': 4000000,
  'position': 'Attack-Centre-Forward',
  'club': 'E. Frankfurt',
  'countries': ['Argentina', 'Italy']},
 {'_id': ObjectId('69d901747943dd8b5d62cfa8'),
  'name': 'Jonas Omlin',
  'age': 29,
  'height': 1.9,
  'price': 7000000,
  'position': 'Goalkeeper',
  'club': "Bor. M'gladbach",
  'countries': ['Switzerland']},
 {'_id': ObjectId('69d901747943dd8b5d62cfaa'),
  'name': 'Tobias Sippel',
  'age': 35,
  'height': 1.83,
  'price': 400000,
  'position': 'Goalkeeper',
  'club': "Bor. M'gladbach",
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cfae'),
  'name': 'Tony Jantschke',
  'age': 33,
  'height': 1.77,
  'price': 800000,
  'position': 'Defender-Centre-Back',
  'club': "Bor. M'gladbach",
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cfb0'),
  'name': 'Ramy Bensebaini',
  'age': 28,
  'height': 1.87,
  'price': 20000000,
  'position': 'Defender-Left-Back',
  'club': "Bor. M'gladbach",
  'countries': ['Algeria']},
 {'_id': ObjectId('69d901747943dd8b5d62cfb3'),
  'name': 'Stefan Lainer',
  'age': 30,
  'height': 1.75,
  'price': 3500000,
  'position': 'Defender-Right-Back',
  'club': "Bor. M'gladbach",
  'countries': ['Austria']},
 {'_id': ObjectId('69d901747943dd8b5d62cfb5'),
  'name': 'Christoph Kramer',
  'age': 32,
  'height': 1.91,
  'price': 2500000,
  'position': 'midfield-DefensiveMidfield',
  'club': "Bor. M'gladbach",
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cfb9'),
  'name': 'Lars Stindl',
  'age': 34,
  'height': 1.81,
  'price': 2500000,
  'position': 'midfield-AttackingMidfield',
  'club': "Bor. M'gladbach",
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cfbb'),
  'name': 'Alassane Plea',
  'age': 30,
  'height': 1.81,
  'price': 10000000,
  'position': 'Attack-LeftWinger',
  'club': "Bor. M'gladbach",
  'countries': ['France', 'Mali']},
 {'_id': ObjectId('69d901747943dd8b5d62cfbe'),
  'name': 'Jonas Hofmann',
  'age': 30,
  'height': 1.76,
  'price': 13000000,
  'position': 'Attack-RightWinger',
  'club': "Bor. M'gladbach",
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cfc0'),
  'name': 'Patrick Herrmann',
  'age': 32,
  'height': 1.79,
  'price': 2000000,
  'position': 'Attack-RightWinger',
  'club': "Bor. M'gladbach",
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cfc2'),
  'name': 'Koen Casteels',
  'age': 30,
  'height': 1.97,
  'price': 8000000,
  'position': 'Goalkeeper',
  'club': 'VfL Wolfsburg',
  'countries': ['Belgium']},
 {'_id': ObjectId('69d901747943dd8b5d62cfc3'),
  'name': 'Pavao Pervan',
  'age': 35,
  'height': 1.94,
  'price': 400000,
  'position': 'Goalkeeper',
  'club': 'VfL Wolfsburg',
  'countries': ['Austria']},
 {'_id': ObjectId('69d901747943dd8b5d62cfc8'),
  'name': 'Paulo Otávio',
  'age': 28,
  'height': 1.73,
  'price': 6500000,
  'position': 'Defender-Left-Back',
  'club': 'VfL Wolfsburg',
  'countries': ['Brazil']},
 {'_id': ObjectId('69d901747943dd8b5d62cfcd'),
  'name': 'Josuha Guilavogui',
  'age': 32,
  'height': 1.88,
  'price': 3000000,
  'position': 'midfield-DefensiveMidfield',
  'club': 'VfL Wolfsburg',
  'countries': ['France', 'Guinea']},
 {'_id': ObjectId('69d901747943dd8b5d62cfce'),
  'name': 'Maximilian Arnold',
  'age': 28,
  'height': 1.84,
  'price': 17000000,
  'position': 'midfield-CentralMidfield',
  'club': 'VfL Wolfsburg',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cfd0'),
  'name': 'Yannick Gerhardt',
  'age': 29,
  'height': 1.84,
  'price': 7000000,
  'position': 'midfield-CentralMidfield',
  'club': 'VfL Wolfsburg',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cfda'),
  'name': 'Mark Flekken',
  'age': 29,
  'height': 1.95,
  'price': 7000000,
  'position': 'Goalkeeper',
  'club': 'SC Freiburg',
  'countries': ['Netherlands']},
 {'_id': ObjectId('69d901747943dd8b5d62cfdc'),
  'name': 'Benjamin Uphoff',
  'age': 29,
  'height': 1.92,
  'price': 500000,
  'position': 'Goalkeeper',
  'club': 'SC Freiburg',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cfde'),
  'name': 'Matthias Ginter',
  'age': 29,
  'height': 1.91,
  'price': 20000000,
  'position': 'Defender-Centre-Back',
  'club': 'SC Freiburg',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cfdf'),
  'name': 'Manuel Gulde',
  'age': 32,
  'height': 1.84,
  'price': 1700000,
  'position': 'Defender-Centre-Back',
  'club': 'SC Freiburg',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cfe1'),
  'name': 'Christian Günter',
  'age': 30,
  'height': 1.84,
  'price': 10000000,
  'position': 'Defender-Left-Back',
  'club': 'SC Freiburg',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cfe4'),
  'name': 'Lukas Kübler',
  'age': 30,
  'height': 1.82,
  'price': 3000000,
  'position': 'Defender-Right-Back',
  'club': 'SC Freiburg',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cfe5'),
  'name': 'Jonathan Schmid',
  'age': 32,
  'height': 1.79,
  'price': 1200000,
  'position': 'Defender-Right-Back',
  'club': 'SC Freiburg',
  'countries': ['France']},
 {'_id': ObjectId('69d901747943dd8b5d62cfe7'),
  'name': 'Nicolas Höfler',
  'age': 33,
  'height': 1.81,
  'price': 2500000,
  'position': 'midfield-DefensiveMidfield',
  'club': 'SC Freiburg',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cfec'),
  'name': 'Vincenzo Grifo',
  'age': 30,
  'height': 1.8,
  'price': 12000000,
  'position': 'Attack-LeftWinger',
  'club': 'SC Freiburg',
  'countries': ['Italy']},
 {'_id': ObjectId('69d901747943dd8b5d62cff1'),
  'name': 'Michael Gregoritsch',
  'age': 29,
  'height': 1.93,
  'price': 8000000,
  'position': 'Attack-Centre-Forward',
  'club': 'SC Freiburg',
  'countries': ['Austria']},
 {'_id': ObjectId('69d901747943dd8b5d62cff2'),
  'name': 'Lucas Höler',
  'age': 28,
  'height': 1.84,
  'price': 5000000,
  'position': 'Attack-Centre-Forward',
  'club': 'SC Freiburg',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cff3'),
  'name': 'Nils Petersen',
  'age': 34,
  'height': 1.88,
  'price': 1500000,
  'position': 'Attack-Centre-Forward',
  'club': 'SC Freiburg',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cff4'),
  'name': 'Oliver Baumann',
  'age': 32,
  'height': 1.87,
  'price': 4500000,
  'position': 'Goalkeeper',
  'club': 'TSG Hoffenheim',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cff5'),
  'name': 'Philipp Pentke',
  'age': 38,
  'height': 1.91,
  'price': 300000,
  'position': 'Goalkeeper',
  'club': 'TSG Hoffenheim',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cffa'),
  'name': 'Kevin Akpoguma',
  'age': 28,
  'height': 1.92,
  'price': 4000000,
  'position': 'Defender-Centre-Back',
  'club': 'TSG Hoffenheim',
  'countries': ['Germany', 'Nigeria']},
 {'_id': ObjectId('69d901747943dd8b5d62cffb'),
  'name': 'Kevin Vogt',
  'age': 31,
  'height': 1.94,
  'price': 3500000,
  'position': 'Defender-Centre-Back',
  'club': 'TSG Hoffenheim',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cffc'),
  'name': 'John Anthony Brooks',
  'age': 30,
  'height': 1.94,
  'price': 3000000,
  'position': 'Defender-Centre-Back',
  'club': 'TSG Hoffenheim',
  'countries': ['United States', 'Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62cffe'),
  'name': 'Ermin Bicakcic',
  'age': 33,
  'height': 1.85,
  'price': 1000000,
  'position': 'Defender-Centre-Back',
  'club': 'TSG Hoffenheim',
  'countries': ['Bosnia-Herzegovina', 'Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62d000'),
  'name': 'Pavel Kaderabek',
  'age': 31,
  'height': 1.82,
  'price': 4000000,
  'position': 'Defender-Right-Back',
  'club': 'TSG Hoffenheim',
  'countries': ['Czech Republic']},
 {'_id': ObjectId('69d901747943dd8b5d62d003'),
  'name': 'Sebastian Rudy',
  'age': 33,
  'height': 1.8,
  'price': 1500000,
  'position': 'midfield-DefensiveMidfield',
  'club': 'TSG Hoffenheim',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62d005'),
  'name': 'Grischa Prömel',
  'age': 28,
  'height': 1.84,
  'price': 7500000,
  'position': 'midfield-CentralMidfield',
  'club': 'TSG Hoffenheim',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62d006'),
  'name': 'Thomas Delaney',
  'age': 31,
  'height': 1.82,
  'price': 3000000,
  'position': 'midfield-CentralMidfield',
  'club': 'TSG Hoffenheim',
  'countries': ['United States', 'Denmark']},
 {'_id': ObjectId('69d901747943dd8b5d62d00f'),
  'name': 'Andrej Kramaric',
  'age': 31,
  'height': 1.77,
  'price': 9000000,
  'position': 'Attack-Centre-Forward',
  'club': 'TSG Hoffenheim',
  'countries': ['Croatia']},
 {'_id': ObjectId('69d901747943dd8b5d62d010'),
  'name': 'Ihlas Bebou',
  'age': 29,
  'height': 1.83,
  'price': 7000000,
  'position': 'Attack-Centre-Forward',
  'club': 'TSG Hoffenheim',
  'countries': ['Germany', 'Togo']},
 {'_id': ObjectId('69d901747943dd8b5d62d011'),
  'name': 'Munas Dabbur',
  'age': 30,
  'height': 1.82,
  'price': 4000000,
  'position': 'Attack-Centre-Forward',
  'club': 'TSG Hoffenheim',
  'countries': ['Israel']},
 {'_id': ObjectId('69d901747943dd8b5d62d013'),
  'name': 'Frederik Rönnow',
  'age': 30,
  'height': 1.88,
  'price': 3500000,
  'position': 'Goalkeeper',
  'club': 'Union Berlin',
  'countries': ['Denmark']},
 {'_id': ObjectId('69d901747943dd8b5d62d015'),
  'name': 'Jakob Busk',
  'age': 29,
  'height': 1.89,
  'price': 250000,
  'position': 'Goalkeeper',
  'club': 'Union Berlin',
  'countries': ['Denmark']},
 {'_id': ObjectId('69d901747943dd8b5d62d019'),
  'name': 'Robin Knoche',
  'age': 30,
  'height': 1.89,
  'price': 5000000,
  'position': 'Defender-Centre-Back',
  'club': 'Union Berlin',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62d01b'),
  'name': 'Jérôme Roussillon',
  'age': 30,
  'height': 1.72,
  'price': 3000000,
  'position': 'Defender-Left-Back',
  'club': 'Union Berlin',
  'countries': ['Guadeloupe', 'France']},
 {'_id': ObjectId('69d901747943dd8b5d62d01c'),
  'name': 'Niko Gießelmann',
  'age': 31,
  'height': 1.82,
  'price': 2000000,
  'position': 'Defender-Left-Back',
  'club': 'Union Berlin',
  'countries': ['Germany']},
 {'_id': ObjectId('69d901747943dd8b5d62d01e'),
  'name': 'Christopher Trimmel',
  'age': 36,
  'height': 1.89,
  'price': 800000,
  'position': 'Defender-Right-Back',

ODM APPROACH

In [69]:
# pip install mongoengine

In [85]:
from mongoengine import connect

connect(
    db="bundesliga",
    host= "mongodb://admin:123@localhost:27017/?authSource=admin"
)

MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True, authsource='admin', read_preference=Primary(), uuidrepresentation=3, driver=DriverInfo(name='MongoEngine', version='0.29.3', platform=None))

In [86]:
from mongoengine import connect

connect(
    db   = "bundesliga",
    host = "mongodb://admin:123@localhost:27017/?authSource=admin"
)

try:
    client = MongoClient("mongodb://admin:123@localhost:27017/?authSource=admin")
    client.server_info()
    print("Connected to MongoDB successfully !!!")
except Exception as e:
    print("Connection failed: ", e)

Connected to MongoDB successfully !!!

In [87]:
### Defining the model
from mongoengine import Document, StringField, IntField, FloatField, ListField

class Players(Document):
    name        = StringField(required = True)
    age         = IntField() 
    height      = FloatField()
    countries   = ListField(StringField())
    price       = IntField()
    max_price   = IntField()
    position    = StringField()
    club        = StringField()

In [88]:
for record in records:
    record.pop('_id', None)
    player = Players(**record)
    player.save()

In [89]:
Players.objects()

[<Players: Players object>, <Players: Players object>, <Players: Players object>, <Players: Players object>, <Players: Players object>, <Players: Players object>, <Players: Players object>, <Players: Players object>, <Players: Players object>, <Players: Players object>, <Players: Players object>, <Players: Players object>, <Players: Players object>, <Players: Players object>, <Players: Players object>, <Players: Players object>, <Players: Players object>, <Players: Players object>, <Players: Players object>, <Players: Players object>, '...(remaining elements truncated)...']

In [90]:
unique_position = Players.objects.distinct("position")
print([unique_position])

[['Attack-Centre-Forward', 'Attack-LeftWinger', 'Attack-RightWinger', 'Attack-SecondStriker', 'Defender-Centre-Back', 'Defender-Left-Back', 'Defender-Right-Back', 'Goalkeeper', 'midfield-AttackingMidfield', 'midfield-CentralMidfield', 'midfield-DefensiveMidfield', 'midfield-LeftMidfield', 'midfield-RightMidfield']]

In [91]:
positions = {
    'Goalkeeper' : 1,
    'Defender-Centre-Back' : 2, 
    'Defender-Left-Back' : 1,
    'Defender-Right-Back' : 1,
    'midfield-AttackingMidfield' : 1,
    'midfield-CentralMidfield' : 1,
    'midfield-DefensiveMidfield' : 1,
    'Attack-Centre-Forward' : 1, 
    'Attack-LeftWinger' : 1, 
    'Attack-RightWinger' : 1
}

starting_XI = []
user_ids = set()
for key, value in positions.items():
    candidates = Players.objects(position__icontains = key).order_by('-price' and 'max_price')

    count = 0
    for candidate in candidates:
        if str(candidate.id) not in user_ids:
            starting_XI.append(candidate)
            user_ids.add(str(candidate.id))
            count += 1 
        
        if count == value:
            break

print("The best eleven is:\n")

for p in starting_XI:
    print(f"{p.name} ({p.countries[0]} international) - {p.position} with market price {p.price:,} EUROS.")

The best eleven is:

Florian Müller (Germany international) - Goalkeeper with market price 1,500,000 EUROS.
Maxim Leitsch (Germany international) - Defender-Centre-Back with market price 3,500,000 EUROS.
Márton Dárdai (Germany international) - Defender-Centre-Back with market price 4,000,000 EUROS.
Kristian Pedersen (Denmark international) - Defender-Left-Back with market price 1,500,000 EUROS.
Jonjoe Kenny (England international) - Defender-Right-Back with market price 4,000,000 EUROS.
Jae-sung Lee (Korea, South international) - midfield-AttackingMidfield with market price 4,000,000 EUROS.
Dominik Kohr (Germany international) - midfield-CentralMidfield with market price 4,000,000 EUROS.
Ivan Sunjic (Croatia international) - midfield-DefensiveMidfield with market price 4,000,000 EUROS.
Nelson Weiper (Albania international) - Attack-Centre-Forward with market price 2,500,000 EUROS.
Vincenzo Grifo (Italy international) - Attack-LeftWinger with market price 12,000,000 EUROS.
Noah Joel Sarenren Bazee (Germany international) - Attack-RightWinger with market price 800,000 EUROS.

In [92]:
start = time.perf_counter()

player = Players.objects(age__gte=25, club = "Bor. Dortmund", position__icontains = "Forward").limit(10)
for p in player:
    print(p.name, p.age, p.position)

end   = time.perf_counter()
time_taken = end - start
print(f"It took {time_taken * 1000:.2f} ms to perform this query")

Sébastien Haller 28 Attack-Centre-Forward
Anthony Modeste 35 Attack-Centre-Forward
It took 2.83 ms to perform this query

In [85]:
Players.objects(age__lt = 20).delete()

44

In [86]:
Players.objects(name = "Dayot Upamecano").update(set__age = 25)

1

In [87]:
new_player = Players(
    name = "Harry Kane",
    age  = 30,
    height = 1.88,
    nationality = "England",
    price = 100000000,
    max_price = 150000000,
    position = "Attack - Centre-Forward",
    club = "Bayern Munich"
)

new_player.save()