In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("C:/Users/Admin/Downloads/bundesliga_player.csv")

In [3]:
from pymongo import MongoClient

client = MongoClient("mongodb://admin:123@localhost:27017/?authSource=admin")
db = client["bundesliga"]
collection = db["players"]

DATA PREPROCESSING

In [4]:
df.isna().sum()

Unnamed: 0            0
name                  0
full_name           286
age                   0
height                0
nationality           0
place_of_birth        5
price                 5
max_price             5
position              0
shirt_nr              0
foot                  9
club                  0
contract_expires     34
joined_club           0
player_agent         27
outfitter           322
dtype: int64

In [5]:
df[df.isna().any(axis=1)]

,Unnamed: 0,name,full_name,age,height,nationality,place_of_birth,price,max_price,position,shirt_nr,foot,club,contract_expires,joined_club,player_agent,outfitter
1,1,Yann Sommer,NaN,34,1.83,Switzerland,Morges,5.0,13.0,Goalkeeper,27,right,Bayern Munich,2025-06-30,2023-01-19,Relatives,Puma
2,2,Sven Ulreich,NaN,34,1.92,Germany,Schorndorf,0.9,6.0,Goalkeeper,26,right,Bayern Munich,2024-06-30,2021-07-01,BMS Sportconsulting ...,adidas
3,3,Johannes Schenk,NaN,20,1.91,Germany,Schweinfurt,0.3,0.3,Goalkeeper,35,NaN,Bayern Munich,2024-06-30,2022-07-01,11WINS,NaN
4,4,Matthijs de Ligt,NaN,23,1.89,Netherlands,Leiderdorp,75.0,75.0,Defender - Centre-Back,4,right,Bayern Munich,2027-06-30,2022-07-19,Rafaela Pimenta,adidas
7,7,Alphonso Davies,Alphonso Boyle Davies,22,1.85,Canada Liberia,Buduburam,70.0,80.0,Defender - Left-Back,19,left,Bayern Munich,2025-06-30,2019-01-01,ATG Sports,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
507,507,Philipp Förster,NaN,28,1.88,Germany,Bretten,2.5,3.5,midfield - Attacking Midfield,10,left,VfL Bochum,2024-06-30,2022-07-01,ROOF,NaN
508,508,Gerrit Holtmann,NaN,28,1.85,Philippines Germany,Bremen,3.5,4.5,Attack - Left Winger,17,left,VfL Bochum,2025-06-30,2020-08-24,Relatives,NaN
509,509,Christopher Antwi-Adjei,NaN,29,1.74,Ghana Germany,Hagen,1.8,2.0,Attack - Left Winger,22,right,VfL Bochum,2024-06-30,2021-07-01,Kay Sports ...,NaN
511,511,Philipp Hofmann,NaN,30,1.95,Germany,Arnsberg,2.5,2.5,Attack - Centre-Forward,33,left,VfL Bochum,2024-06-30,2022-07-01,ROOF,NaN
514,514,Moritz Broschinski,NaN,22,1.90,Germany,Finsterwalde,0.5,0.5,Attack - Centre-Forward,29,right,VfL Bochum,2026-06-30,2023-01-22,Teamgeist ...,NaN

In [6]:
df = df.dropna(how = "all")

In [7]:
# Step 1: inspect
print(df.isna().sum())
print(df[df.isna().any(axis=1)])

# Step 2: clean
df = df.dropna()
print(df.isna().sum())

Unnamed: 0            0
name                  0
full_name           286
age                   0
height                0
nationality           0
place_of_birth        5
price                 5
max_price             5
position              0
shirt_nr              0
foot                  9
club                  0
contract_expires     34
joined_club           0
player_agent         27
outfitter           322
dtype: int64
     Unnamed: 0                     name              full_name  age  height  \
1             1              Yann Sommer                    NaN   34    1.83
2             2             Sven Ulreich                    NaN   34    1.92
3             3          Johannes Schenk                    NaN   20    1.91
4             4         Matthijs de Ligt                    NaN   23    1.89
7             7          Alphonso Davies  Alphonso Boyle Davies   22    1.85
..          ...                      ...                    ...  ...     ...
507         507          Philipp Förster                    NaN   28    1.88
508         508          Gerrit Holtmann                    NaN   28    1.85
509         509  Christopher Antwi-Adjei                    NaN   29    1.74
511         511          Philipp Hofmann                    NaN   30    1.95
514         514       Moritz Broschinski                    NaN   22    1.90

              nationality place_of_birth  price  max_price  \
1             Switzerland         Morges    5.0       13.0
2                 Germany     Schorndorf    0.9        6.0
3                 Germany    Schweinfurt    0.3        0.3
4             Netherlands     Leiderdorp   75.0       75.0
7         Canada  Liberia      Buduburam   70.0       80.0
..                    ...            ...    ...        ...
507               Germany        Bretten    2.5        3.5
508  Philippines  Germany         Bremen    3.5        4.5
509        Ghana  Germany          Hagen    1.8        2.0
511               Germany       Arnsberg    2.5        2.5
514               Germany   Finsterwalde    0.5        0.5

                          position  shirt_nr   foot           club  \
1                       Goalkeeper        27  right  Bayern Munich
2                       Goalkeeper        26  right  Bayern Munich
3                       Goalkeeper        35    NaN  Bayern Munich
4           Defender - Centre-Back         4  right  Bayern Munich
7             Defender - Left-Back        19   left  Bayern Munich
..                             ...       ...    ...            ...
507  midfield - Attacking Midfield        10   left     VfL Bochum
508           Attack - Left Winger        17   left     VfL Bochum
509           Attack - Left Winger        22  right     VfL Bochum
511        Attack - Centre-Forward        33   left     VfL Bochum
514        Attack - Centre-Forward        29  right     VfL Bochum

    contract_expires joined_club             player_agent outfitter
1         2025-06-30  2023-01-19                Relatives      Puma
2         2024-06-30  2021-07-01  BMS Sportconsulting ...    adidas
3         2024-06-30  2022-07-01                   11WINS       NaN
4         2027-06-30  2022-07-19          Rafaela Pimenta    adidas
7         2025-06-30  2019-01-01               ATG Sports       NaN
..               ...         ...                      ...       ...
507       2024-06-30  2022-07-01                     ROOF       NaN
508       2025-06-30  2020-08-24                Relatives       NaN
509       2024-06-30  2021-07-01           Kay Sports ...       NaN
511       2024-06-30  2022-07-01                     ROOF       NaN
514       2026-06-30  2023-01-22            Teamgeist ...       NaN

[439 rows x 17 columns]
Unnamed: 0          0
name                0
full_name           0
age                 0
height              0
nationality         0
place_of_birth      0
price               0
max_price           0
position            0
shirt_nr            0
foot                0
club                0
contract_expires    0
joined_club         0
player_agent        0
outfitter           0
dtype: int64

In [8]:
df = df.reset_index(drop=True)

In [9]:
df.columns = [col.strip().lower().replace(" ", "_") for col in df.columns]

In [10]:
df

,unnamed:_0,name,full_name,age,height,nationality,place_of_birth,price,max_price,position,shirt_nr,foot,club,contract_expires,joined_club,player_agent,outfitter
0,0,Manuel Neuer,Manuel Peter Neuer,37,1.93,Germany,Gelsenkirchen,7.00,45.0,Goalkeeper,1,right,Bayern Munich,2024-06-30,2011-07-01,PRO Profil GmbH,adidas
1,5,Dayot Upamecano,Dayotchanculle Oswald Upamecano,24,1.86,France Guinea-Bissau,Évreux,60.00,60.0,Defender - Centre-Back,2,right,Bayern Munich,2026-06-30,2021-07-05,Unique Sports Group,Nike
2,6,Lucas Hernández,Lucas François Bernard Hernández Pi,27,1.84,France Spain,Marseille,50.00,70.0,Defender - Centre-Back,21,left,Bayern Munich,2024-06-30,2019-07-01,Manuel García ...,Nike
3,9,João Cancelo,João Pedro Cavaco Cancelo,28,1.82,Portugal,Barreiro,60.00,70.0,Defender - Right-Back,22,right,Bayern Munich,2023-06-30,2023-01-31,Gestifute,Nike
4,11,Noussair Mazraoui,نصير مزراوي,25,1.83,Morocco Netherlands,Leiderdorp,28.00,28.0,Defender - Right-Back,40,right,Bayern Munich,2026-06-30,2022-07-01,Rafaela Pimenta,adidas
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,463,Maya Yoshida,吉田 麻也,34,1.89,Japan,"Nagasaki, Nagasaki",1.50,7.0,Defender - Centre-Back,4,right,FC Schalke 04,2023-06-30,2022-07-05,CAA Base Ltd,Mizuno
72,472,Alex Kral,Alex Král,24,1.86,Czech Republic Slovakia,Košice,5.50,10.0,midfield - Defensive Midfield,30,right,FC Schalke 04,2023-06-30,2022-07-14,K2K Sports ...,Nike
73,510,Takuma Asano,浅野 拓磨,28,1.73,Japan,"Komono, Mie",4.00,4.0,Attack - Right Winger,11,right,VfL Bochum,2024-06-30,2021-07-01,JEB ENTERTAINMENT ...,adidas
74,512,Simon Zoller,Simon Martin Zoller,31,1.79,Germany,Friedrichshafen,1.10,3.0,Attack - Centre-Forward,9,right,VfL Bochum,2024-06-30,2019-01-01,GoalSky,Puma
75,513,Silvère Ganvoula,Silvère Ganvoula M'boussy,26,1.91,Congo,Brazzaville,0.75,2.5,Attack - Centre-Forward,35,right,VfL Bochum,2023-06-30,2019-07-05,BY Sport Consulting,Puma

In [11]:
df.drop(["unnamed:_0", "full_name", "place_of_birth","shirt_nr", "foot", "contract_expires", "joined_club", "player_agent", "outfitter"], inplace = True, axis = 1 )

In [12]:
df

,name,age,height,nationality,price,max_price,position,club
0,Manuel Neuer,37,1.93,Germany,7.00,45.0,Goalkeeper,Bayern Munich
1,Dayot Upamecano,24,1.86,France Guinea-Bissau,60.00,60.0,Defender - Centre-Back,Bayern Munich
2,Lucas Hernández,27,1.84,France Spain,50.00,70.0,Defender - Centre-Back,Bayern Munich
3,João Cancelo,28,1.82,Portugal,60.00,70.0,Defender - Right-Back,Bayern Munich
4,Noussair Mazraoui,25,1.83,Morocco Netherlands,28.00,28.0,Defender - Right-Back,Bayern Munich
...,...,...,...,...,...,...,...,...
71,Maya Yoshida,34,1.89,Japan,1.50,7.0,Defender - Centre-Back,FC Schalke 04
72,Alex Kral,24,1.86,Czech Republic Slovakia,5.50,10.0,midfield - Defensive Midfield,FC Schalke 04
73,Takuma Asano,28,1.73,Japan,4.00,4.0,Attack - Right Winger,VfL Bochum
74,Simon Zoller,31,1.79,Germany,1.10,3.0,Attack - Centre-Forward,VfL Bochum
75,Silvère Ganvoula,26,1.91,Congo,0.75,2.5,Attack - Centre-Forward,VfL Bochum

In [13]:
df['price']     = df['price'].apply(lambda x : f"{x} euros")
df['max_price'] = df['max_price'].apply(lambda x : f"{x} euros")

In [14]:
# print(df['max_price'].unique())

In [15]:
df['price']     = df['price'].str.split().str[0].astype(float)     * 1_000_000
df['max_price'] = df['max_price'].str.split().str[0].astype(float) * 1_000_000

In [16]:
df['price']     = df['price'].astype(int).map("{:,}".format)     + " euros"
df['max_price'] = df['max_price'].astype(int).map("{:,}".format) + " euros"

In [17]:
df

,name,age,height,nationality,price,max_price,position,club
0,Manuel Neuer,37,1.93,Germany,"7,000,000 euros","45,000,000 euros",Goalkeeper,Bayern Munich
1,Dayot Upamecano,24,1.86,France Guinea-Bissau,"60,000,000 euros","60,000,000 euros",Defender - Centre-Back,Bayern Munich
2,Lucas Hernández,27,1.84,France Spain,"50,000,000 euros","70,000,000 euros",Defender - Centre-Back,Bayern Munich
3,João Cancelo,28,1.82,Portugal,"60,000,000 euros","70,000,000 euros",Defender - Right-Back,Bayern Munich
4,Noussair Mazraoui,25,1.83,Morocco Netherlands,"28,000,000 euros","28,000,000 euros",Defender - Right-Back,Bayern Munich
...,...,...,...,...,...,...,...,...
71,Maya Yoshida,34,1.89,Japan,"1,500,000 euros","7,000,000 euros",Defender - Centre-Back,FC Schalke 04
72,Alex Kral,24,1.86,Czech Republic Slovakia,"5,500,000 euros","10,000,000 euros",midfield - Defensive Midfield,FC Schalke 04
73,Takuma Asano,28,1.73,Japan,"4,000,000 euros","4,000,000 euros",Attack - Right Winger,VfL Bochum
74,Simon Zoller,31,1.79,Germany,"1,100,000 euros","3,000,000 euros",Attack - Centre-Forward,VfL Bochum
75,Silvère Ganvoula,26,1.91,Congo,"750,000 euros","2,500,000 euros",Attack - Centre-Forward,VfL Bochum

In [18]:
df.dtypes

name               str
age              int64
height         float64
nationality        str
price              str
max_price          str
position           str
club               str
dtype: object

In [19]:
print(df['position'].nunique())

11

In [20]:
# We do this before sending df as records to DB. If we don't we won't be able to do filtering, aggregations, and etc.
df['price']     = (df['price'].str.replace(',', '').str.replace(' euros', '').astype(float).astype(int))
df['max_price'] = (df['max_price'].str.replace(',', '').str.replace(' euros', '').astype(float).astype(int))

INSERTING DATA TO MONGODB

In [21]:
records = df.to_dict(orient='records')

In [22]:
records

[{'name': 'Manuel Neuer',
  'age': 37,
  'height': 1.93,
  'nationality': 'Germany',
  'price': 7000000,
  'max_price': 45000000,
  'position': 'Goalkeeper',
  'club': 'Bayern Munich'},
 {'name': 'Dayot Upamecano',
  'age': 24,
  'height': 1.86,
  'nationality': 'France\xa0\xa0Guinea-Bissau',
  'price': 60000000,
  'max_price': 60000000,
  'position': 'Defender - Centre-Back',
  'club': 'Bayern Munich'},
 {'name': 'Lucas Hernández',
  'age': 27,
  'height': 1.84,
  'nationality': 'France\xa0\xa0Spain',
  'price': 50000000,
  'max_price': 70000000,
  'position': 'Defender - Centre-Back',
  'club': 'Bayern Munich'},
 {'name': 'João Cancelo',
  'age': 28,
  'height': 1.82,
  'nationality': 'Portugal',
  'price': 60000000,
  'max_price': 70000000,
  'position': 'Defender - Right-Back',
  'club': 'Bayern Munich'},
 {'name': 'Noussair Mazraoui',
  'age': 25,
  'height': 1.83,
  'nationality': 'Morocco\xa0\xa0Netherlands',
  'price': 28000000,
  'max_price': 28000000,
  'position': 'Defender - Right-Back',
  'club': 'Bayern Munich'},
 {'name': 'Josip Stanisic',
  'age': 23,
  'height': 1.87,
  'nationality': 'Croatia\xa0\xa0Germany',
  'price': 12000000,
  'max_price': 12000000,
  'position': 'Defender - Right-Back',
  'club': 'Bayern Munich'},
 {'name': 'Ryan Gravenberch',
  'age': 20,
  'height': 1.9,
  'nationality': 'Netherlands\xa0\xa0Suriname',
  'price': 30000000,
  'max_price': 35000000,
  'position': 'midfield - Central Midfield',
  'club': 'Bayern Munich'},
 {'name': 'Kingsley Coman',
  'age': 26,
  'height': 1.81,
  'nationality': 'France\xa0\xa0Guadeloupe',
  'price': 65000000,
  'max_price': 65000000,
  'position': 'Attack - Left Winger',
  'club': 'Bayern Munich'},
 {'name': 'Leroy Sané',
  'age': 27,
  'height': 1.83,
  'nationality': 'Germany\xa0\xa0France',
  'price': 70000000,
  'max_price': 100000000,
  'position': 'Attack - Right Winger',
  'club': 'Bayern Munich'},
 {'name': 'Serge Gnabry',
  'age': 27,
  'height': 1.76,
  'nationality': "Germany\xa0\xa0Cote d'Ivoire",
  'price': 55000000,
  'max_price': 90000000,
  'position': 'Attack - Right Winger',
  'club': 'Bayern Munich'},
 {'name': 'Eric Maxim Choupo-Moting',
  'age': 34,
  'height': 1.91,
  'nationality': 'Cameroon\xa0\xa0Germany',
  'price': 6000000,
  'max_price': 10000000,
  'position': 'Attack - Centre-Forward',
  'club': 'Bayern Munich'},
 {'name': 'Mats Hummels',
  'age': 34,
  'height': 1.91,
  'nationality': 'Germany',
  'price': 6500000,
  'max_price': 60000000,
  'position': 'Defender - Centre-Back',
  'club': 'Bor. Dortmund'},
 {'name': 'Raphaël Guerreiro',
  'age': 29,
  'height': 1.7,
  'nationality': 'Portugal\xa0\xa0France',
  'price': 20000000,
  'max_price': 40000000,
  'position': 'Defender - Left-Back',
  'club': 'Bor. Dortmund'},
 {'name': 'Giovanni Reyna',
  'age': 20,
  'height': 1.85,
  'nationality': 'United States\xa0\xa0Portugal',
  'price': 28000000,
  'max_price': 42000000,
  'position': 'midfield - Attacking Midfield',
  'club': 'Bor. Dortmund'},
 {'name': 'Karim Adeyemi',
  'age': 21,
  'height': 1.8,
  'nationality': 'Germany\xa0\xa0Nigeria',
  'price': 35000000,
  'max_price': 35000000,
  'position': 'Attack - Left Winger',
  'club': 'Bor. Dortmund'},
 {'name': 'Sébastien Haller',
  'age': 28,
  'height': 1.91,
  'nationality': "Cote d'Ivoire\xa0\xa0France",
  'price': 30000000,
  'max_price': 45000000,
  'position': 'Attack - Centre-Forward',
  'club': 'Bor. Dortmund'},
 {'name': 'Janis Blaswich',
  'age': 32,
  'height': 1.93,
  'nationality': 'Germany',
  'price': 2000000,
  'max_price': 2000000,
  'position': 'Goalkeeper',
  'club': 'RB Leipzig'},
 {'name': 'Abdou Diallo',
  'age': 27,
  'height': 1.87,
  'nationality': 'Senegal\xa0\xa0France',
  'price': 15000000,
  'max_price': 35000000,
  'position': 'Defender - Centre-Back',
  'club': 'RB Leipzig'},
 {'name': 'Willi Orbán',
  'age': 30,
  'height': 1.86,
  'nationality': 'Hungary\xa0\xa0Germany',
  'price': 10000000,
  'max_price': 20000000,
  'position': 'Defender - Centre-Back',
  'club': 'RB Leipzig'},
 {'name': 'Christopher Nkunku',
  'age': 25,
  'height': 1.78,
  'nationality': 'France\xa0\xa0DR Congo',
  'price': 80000000,
  'max_price': 80000000,
  'position': 'Attack - Second Striker',
  'club': 'RB Leipzig'},
 {'name': 'André Silva',
  'age': 27,
  'height': 1.85,
  'nationality': 'Portugal',
  'price': 20000000,
  'max_price': 45000000,
  'position': 'Attack - Centre-Forward',
  'club': 'RB Leipzig'},
 {'name': 'Piero Hincapié',
  'age': 21,
  'height': 1.83,
  'nationality': 'Ecuador',
  'price': 25000000,
  'max_price': 25000000,
  'position': 'Defender - Centre-Back',
  'club': 'B. Leverkusen'},
 {'name': 'Jonathan Tah',
  'age': 27,
  'height': 1.95,
  'nationality': 'Germany',
  'price': 20000000,
  'max_price': 40000000,
  'position': 'Defender - Centre-Back',
  'club': 'B. Leverkusen'},
 {'name': 'Jeremie Frimpong',
  'age': 22,
  'height': 1.71,
  'nationality': 'Netherlands\xa0\xa0Ghana',
  'price': 35000000,
  'max_price': 35000000,
  'position': 'Defender - Right-Back',
  'club': 'B. Leverkusen'},
 {'name': 'Florian Wirtz',
  'age': 20,
  'height': 1.76,
  'nationality': 'Germany',
  'price': 85000000,
  'max_price': 85000000,
  'position': 'midfield - Attacking Midfield',
  'club': 'B. Leverkusen'},
 {'name': 'Callum Hudson-Odoi',
  'age': 22,
  'height': 1.77,
  'nationality': 'England\xa0\xa0Ghana',
  'price': 17000000,
  'max_price': 35000000,
  'position': 'Attack - Left Winger',
  'club': 'B. Leverkusen'},
 {'name': 'Adam Hlozek',
  'age': 20,
  'height': 1.88,
  'nationality': 'Czech Republic',
  'price': 15000000,
  'max_price': 20000000,
  'position': 'Attack - Centre-Forward',
  'club': 'B. Leverkusen'},
 {'name': 'Sardar Azmoun',
  'age': 28,
  'height': 1.86,
  'nationality': 'Iran',
  'price': 12000000,
  'max_price': 25000000,
  'position': 'Attack - Centre-Forward',
  'club': 'B. Leverkusen'},
 {'name': 'Kevin Trapp',
  'age': 32,
  'height': 1.89,
  'nationality': 'Germany',
  'price': 8500000,
  'max_price': 12000000,
  'position': 'Goalkeeper',
  'club': 'E. Frankfurt'},
 {'name': 'Makoto Hasebe',
  'age': 39,
  'height': 1.8,
  'nationality': 'Japan',
  'price': 800000,
  'max_price': 5000000,
  'position': 'Defender - Centre-Back',
  'club': 'E. Frankfurt'},
 {'name': 'Daichi Kamada',
  'age': 26,
  'height': 1.84,
  'nationality': 'Japan',
  'price': 30000000,
  'max_price': 30000000,
  'position': 'midfield - Attacking Midfield',
  'club': 'E. Frankfurt'},
 {'name': 'Jesper Lindström',
  'age': 23,
  'height': 1.82,
  'nationality': 'Denmark',
  'price': 28000000,
  'max_price': 28000000,
  'position': 'midfield - Attacking Midfield',
  'club': 'E. Frankfurt'},
 {'name': 'Lucas Alario',
  'age': 30,
  'height': 1.85,
  'nationality': 'Argentina\xa0\xa0Italy',
  'price': 4000000,
  'max_price': 20000000,
  'position': 'Attack - Centre-Forward',
  'club': 'E. Frankfurt'},
 {'name': 'Jan Olschowsky',
  'age': 21,
  'height': 1.84,
  'nationality': 'Germany',
  'price': 500000,
  'max_price': 500000,
  'position': 'Goalkeeper',
  'club': "Bor. M'gladbach"},
 {'name': 'Ko Itakura',
  'age': 26,
  'height': 1.88,
  'nationality': 'Japan',
  'price': 12000000,
  'max_price': 12000000,
  'position': 'Defender - Centre-Back',
  'club': "Bor. M'gladbach"},
 {'name': 'Joe Scally',
  'age': 20,
  'height': 1.84,
  'nationality': 'United States',
  'price': 12000000,
  'max_price': 12000000,
  'position': 'Defender - Right-Back',
  'club': "Bor. M'gladbach"},
 {'name': 'Manu Koné',
  'age': 21,
  'height': 1.85,
  'nationality': "France\xa0\xa0Cote d'Ivoire",
  'price': 30000000,
  'max_price': 30000000,
  'position': 'midfield - Central Midfield',
  'club': "Bor. M'gladbach"},
 {'name': 'Oscar Fraulo',
  'age': 19,
  'height': 1.8,
  'nationality': 'Denmark\xa0\xa0Italy',
  'price': 2000000,
  'max_price': 2000000,
  'position': 'midfield - Central Midfield',
  'club': "Bor. M'gladbach"},
 {'name': 'Nathan Ngoumou',
  'age': 23,
  'height': 1.83,
  'nationality': 'France\xa0\xa0Cameroon',
  'price': 5000000,
  'max_price': 7000000,
  'position': 'Attack - Right Winger',
  'club': "Bor. M'gladbach"},
 {'name': 'Marcus Thuram',
  'age': 25,
  'height': 1.92,
  'nationality': 'France\xa0\xa0Guadeloupe',
  'price': 32000000,
  'max_price': 40000000,
  'position': 'Attack - Centre-Forward',
  'club': "Bor. M'gladbach"},
 {'name': 'Ridle Baku',
  'age': 25,
  'height': 1.76,
  'nationality': 'Germany\xa0\xa0DR Congo',
  'price': 13000000,
  'max_price': 25000000,
  'position': 'Defender - Right-Back',
  'club': 'VfL Wolfsburg'},
 {'name': 'Jakub Kaminski',
  'age': 20,
  'height': 1.79,
  'nationality': 'Poland',
  'price': 10000000,
  'max_price': 10000000,
  'position': 'Attack - Left Winger',
  'club': 'VfL Wolfsburg'},
 {'name': 'Ozan Kabak',
  'age': 23,
  'height': 1.87,
  'nationality': 'Turkey',
  'price': 10000000,
  'max_price': 32000000,
  'position': 'Defender - Centre-Back',
  'club': 'TSG Hoffenheim'},
 {'name': 'Kevin Akpoguma',
  'age': 28,
  'height': 1.92,
  'nationality': 'Nigeria\xa0\xa0Germany',
  'price': 4000000,
  'max_price': 12000000,
  'position': 'Defender - Centre-Back',
  'club': 'TSG Hoffenheim'},
 {'name': 'Eduardo Quaresma',
  'age': 21,
  'height': 1.85,
  'nationality': 'Portugal',
  'price': 3000000,
  'max_price': 7000000,
  'position': 'Defender - Centre-Back',
  'club': 'TSG Hoffenheim'},
 {'name': 'Ermin Bicakcic',
  'age': 33,
  'height': 1.85,
  'nationality': 'Bosnia-Herzegovina\xa0\xa0Germany',
  'price': 1000000,
  'max_price': 4000000,
  'position': 'Defender - Centre-Back',
  'club': 'TSG Hoffenheim'},
 {'name': 'Justin Che',
  'age': 19,
  'height': 1.85,
  'nationality': 'United States\xa0\xa0Germany',
  'price': 2000000,
  'max_price': 3000000,
  'position': 'Defender - Right-Back',
  'club': 'TSG Hoffenheim'},
 {'name': 'Umut Tohumcu',
  'age': 18,
  'height': 1.75,
  'nationality': 'Germany\xa0\xa0Turkey',
  'price': 1000000,
  'max_price': 1000000,
  'position': 'midfield - Central Midfield',
  'club': 'TSG Hoffenheim'},
 {'name': 'Kasper Dolberg',
  'age': 25,
  'height': 1.87,
  'nationality': 'Denmark',
  'price': 9000000,
  'max_price': 23000000,
  'position': 'Attack - Centre-Forward',
  'club': 'TSG Hoffenheim'},
 {'name': 'Munas Dabbur',
  'age': 30,
  'height': 1.82,
  'nationality': 'Israel',
  'price': 4000000,
  'max_price': 15000000,
  'position': 'Attack - Centre-Forward',
  'club': 'TSG Hoffenheim'},
 {'name': 'Frederik Rönnow',
  'age': 30,
  'height': 1.88,
  'nationality': 'Denmark',
  'price': 3500000,
  'max_price': 3500000,
  'position': 'Goalkeeper',
  'club': 'Union Berlin'},
 {'name': 'Rafal Gikiewicz',
  'age': 35,
  'height': 1.9,
  'nationality': 'Poland',
  'price': 1200000,
  'max_price': 1500000,
  'position': 'Goalkeeper',
  'club': 'FC Augsburg'},
 {'name': 'Felix Uduokhai',
  'age': 25,
  'height': 1.92,
  'nationality': 'Germany\xa0\xa0Nigeria',
  'price': 10000000,
  'max_price': 16000000,
  'position': 'Defender - Centre-Back',
  'club': 'FC Augsburg'},
 {'name': 'Mads Pedersen',
  'age': 26,
  'height': 1.74,
  'nationality': 'Denmark',
  'price': 2500000,
  'max_price': 2500000,
  'position': 'Defender - Left-Back',
  'club': 'FC Augsburg'},
 {'name': 'David Colina',
  'age': 22,
  'height': 1.74,
  'nationality': 'Croatia',
  'price': 1500000,
  'max_price': 1500000,
  'position': 'Defender - Left-Back',
  'club': 'FC Augsburg'},
 {'name': 'Ermedin Demirovic',
  'age': 25,
  'height': 1.85,
  'nationality': 'Bosnia-Herzegovina\xa0\xa0Germany',
  'price': 12000000,
  'max_price': 12000000,
  'position': 'Attack - Centre-Forward',
  'club': 'FC Augsburg'},
 {'name': 'Waldemar Anton',
  'age': 26,
  'height': 1.89,
  'nationality': 'Germany',
  'price': 4500000,
  'max_price': 15000000,
  'position': 'Defender - Centre-Back',
  'club': 'VfB Stuttgart'},
 {'name': 'Josha Vagnoman',
  'age': 22,
  'height': 1.9,
  'nationality': "Germany\xa0\xa0Cote d'Ivoire",
  'price': 5000000,
  'max_price': 5000000,
  'position': 'Defender - Right-Back',
  'club': 'VfB Stuttgart'},
 {'name': 'Wataru Endo',
  'age': 30,
  'height': 1.78,
  'nationality': 'Japan',
  'price': 6500000,
  'max_price': 10000000,
  'position': 'midfield - Defensive Midfield',
  'club': 'VfB Stuttgart'},
 {'name': 'Genki Haraguchi',
  'age': 32,
  'height': 1.78,
  'nationality': 'Japan',
  'price': 2000000,
  'max_price': 4500000,
  'position': 'midfield - Attacking Midfield',
  'club': 'VfB Stuttgart'},
 {'name': 'Ömer Beyaz',
  'age': 19,
  'height': 1.71,
  'nationality': 'Turkey',
  'price': 700000,
  'max_price': 1000000,
  'position': 'midfield - Attacking Midfield',
  'club': 'VfB Stuttgart'},
 {'name': 'Gil Dias',
  'age': 26,
  'height': 1.86,
  'nationality': 'Portugal',
  'price': 2000000,
  'max_price': 4000000,
  'position': 'Attack - Right Winger',
  'club': 'VfB Stuttgart'},
 {'name': 'Juan José Perea',
  'age': 23,
  'height': 1.8,
  'nationality': 'Colombia',
  'price': 2400000,
  'max_price': 2400000,
  'position': 'Attack - Centre-Forward',
  'club': 'VfB Stuttgart'},
 {'name': 'Danny da Costa',
  'age': 29,
  'height': 1.87,
  'nationality': 'Germany\xa0\xa0Angola',
  'price': 2000000,
  'max_price': 15000000,
  'position': 'Defender - Right-Back',
  'club': '1.FSV Mainz 05'},
 {'name': 'Marlon Mustapha',
  'age': 21,
  'height': 1.85,
  'nationality': 'Austria',
  'price': 1000000,
  'max_price': 1000000,
  'position': 'Attack - Centre-Forward',
  'club': '1.FSV Mainz 05'},
 {'name': 'Denis Huseinbasic',
  'age': 21,
  'height': 1.84,
  'nationality': 'Germany\xa0\xa0Bosnia-Herzegovina',
  'price': 5000000,
  'max_price': 5000000,
  'position': 'midfield - Central Midfield',
  'club': '1.FC Köln'},
 {'name': 'Filip Uremovic',
  'age': 26,
  'height': 1.84,
  'nationality': 'Croatia',
  'price': 2000000,
  'max_price': 7000000,
  'position': 'Defender - Centre-Back',
  'club': 'Hertha BSC'},
 {'name': 'Dodi Lukébakio',
  'age': 25,
  'height': 1.87,
  'nationality': 'Belgium\xa0\xa0DR Congo',
  'price': 12000000,
  'max_price': 21000000,
  'position': 'Attack - Right Winger',
  'club': 'Hertha BSC'},
 {'name': 'Jens Stage',
  'age': 26,
  'height': 1.87,
  'nationality': 'Denmark',
  'price': 3500000,
  'max_price': 4000000,
  'position': 'midfield - Central Midfield',
  'club': 'Werder Bremen'},
 {'name': 'Niklas Schmidt',
  'age': 25,
  'height': 1.84,
  'nationality': 'Germany',
  'price': 2500000,
  'max_price': 2500000,
  'position': 'midfield - Attacking Midfield',
  'club': 'Werder Bremen'},
 {'name': 'Ralf Fährmann',
  'age': 34,
  'height': 1.97,
  'nationality': 'Germany',
  'price': 400000,
  'max_price': 13000000,
  'position': 'Goalkeeper',
  'club': 'FC Schalke 04'},
 {'name': 'Maya Yoshida',
  'age': 34,
  'height': 1.89,
  'nationality': 'Japan',
  'price': 1500000,
  'max_price': 7000000,
  'position': 'Defender - Centre-Back',
  'club': 'FC Schalke 04'},
 {'name': 'Alex Kral',
  'age': 24,
  'height': 1.86,
  'nationality': 'Czech Republic\xa0\xa0Slovakia',
  'price': 5500000,
  'max_price': 10000000,
  'position': 'midfield - Defensive Midfield',
  'club': 'FC Schalke 04'},
 {'name': 'Takuma Asano',
  'age': 28,
  'height': 1.73,
  'nationality': 'Japan',
  'price': 4000000,
  'max_price': 4000000,
  'position': 'Attack - Right Winger',
  'club': 'VfL Bochum'},
 {'name': 'Simon Zoller',
  'age': 31,
  'height': 1.79,
  'nationality': 'Germany',
  'price': 1100000,
  'max_price': 3000000,
  'position': 'Attack - Centre-Forward',
  'club': 'VfL Bochum'},
 {'name': 'Silvère Ganvoula',
  'age': 26,
  'height': 1.91,
  'nationality': 'Congo',
  'price': 750000,
  'max_price': 2500000,
  'position': 'Attack - Centre-Forward',
  'club': 'VfL Bochum'}]

In [23]:

import time

start = time.perf_counter()

batch_size = 76

for i in range(0, len(records), batch_size):
    batch = records[i:i + batch_size]
    collection.insert_many(batch)
    print(f"Inserted {i // batch_size + 1}.batch  with {len(batch)} records.")

end = time.perf_counter()
print(end - start)

Inserted 1.batch  with 76 records.
0.025828200043179095

In [24]:
start = time.perf_counter()

results = list(collection.find())

end = time.perf_counter()

time_taken = end - start
print(f"Query Time: {time_taken * 1000:.2f} ms")
print(f"Documents fetched: {len(results)}")

Query Time: 2.02 ms
Documents fetched: 76

In [25]:
results

[{'_id': ObjectId('69d50826639fbfcf435c01b0'),
  'name': 'Manuel Neuer',
  'age': 37,
  'height': 1.93,
  'nationality': 'Germany',
  'price': 7000000,
  'max_price': 45000000,
  'position': 'Goalkeeper',
  'club': 'Bayern Munich'},
 {'_id': ObjectId('69d50826639fbfcf435c01b1'),
  'name': 'Dayot Upamecano',
  'age': 24,
  'height': 1.86,
  'nationality': 'France\xa0\xa0Guinea-Bissau',
  'price': 60000000,
  'max_price': 60000000,
  'position': 'Defender - Centre-Back',
  'club': 'Bayern Munich'},
 {'_id': ObjectId('69d50826639fbfcf435c01b2'),
  'name': 'Lucas Hernández',
  'age': 27,
  'height': 1.84,
  'nationality': 'France\xa0\xa0Spain',
  'price': 50000000,
  'max_price': 70000000,
  'position': 'Defender - Centre-Back',
  'club': 'Bayern Munich'},
 {'_id': ObjectId('69d50826639fbfcf435c01b3'),
  'name': 'João Cancelo',
  'age': 28,
  'height': 1.82,
  'nationality': 'Portugal',
  'price': 60000000,
  'max_price': 70000000,
  'position': 'Defender - Right-Back',
  'club': 'Bayern Munich'},
 {'_id': ObjectId('69d50826639fbfcf435c01b4'),
  'name': 'Noussair Mazraoui',
  'age': 25,
  'height': 1.83,
  'nationality': 'Morocco\xa0\xa0Netherlands',
  'price': 28000000,
  'max_price': 28000000,
  'position': 'Defender - Right-Back',
  'club': 'Bayern Munich'},
 {'_id': ObjectId('69d50826639fbfcf435c01b5'),
  'name': 'Josip Stanisic',
  'age': 23,
  'height': 1.87,
  'nationality': 'Croatia\xa0\xa0Germany',
  'price': 12000000,
  'max_price': 12000000,
  'position': 'Defender - Right-Back',
  'club': 'Bayern Munich'},
 {'_id': ObjectId('69d50826639fbfcf435c01b6'),
  'name': 'Ryan Gravenberch',
  'age': 20,
  'height': 1.9,
  'nationality': 'Netherlands\xa0\xa0Suriname',
  'price': 30000000,
  'max_price': 35000000,
  'position': 'midfield - Central Midfield',
  'club': 'Bayern Munich'},
 {'_id': ObjectId('69d50826639fbfcf435c01b7'),
  'name': 'Kingsley Coman',
  'age': 26,
  'height': 1.81,
  'nationality': 'France\xa0\xa0Guadeloupe',
  'price': 65000000,
  'max_price': 65000000,
  'position': 'Attack - Left Winger',
  'club': 'Bayern Munich'},
 {'_id': ObjectId('69d50826639fbfcf435c01b8'),
  'name': 'Leroy Sané',
  'age': 27,
  'height': 1.83,
  'nationality': 'Germany\xa0\xa0France',
  'price': 70000000,
  'max_price': 100000000,
  'position': 'Attack - Right Winger',
  'club': 'Bayern Munich'},
 {'_id': ObjectId('69d50826639fbfcf435c01b9'),
  'name': 'Serge Gnabry',
  'age': 27,
  'height': 1.76,
  'nationality': "Germany\xa0\xa0Cote d'Ivoire",
  'price': 55000000,
  'max_price': 90000000,
  'position': 'Attack - Right Winger',
  'club': 'Bayern Munich'},
 {'_id': ObjectId('69d50826639fbfcf435c01ba'),
  'name': 'Eric Maxim Choupo-Moting',
  'age': 34,
  'height': 1.91,
  'nationality': 'Cameroon\xa0\xa0Germany',
  'price': 6000000,
  'max_price': 10000000,
  'position': 'Attack - Centre-Forward',
  'club': 'Bayern Munich'},
 {'_id': ObjectId('69d50826639fbfcf435c01bb'),
  'name': 'Mats Hummels',
  'age': 34,
  'height': 1.91,
  'nationality': 'Germany',
  'price': 6500000,
  'max_price': 60000000,
  'position': 'Defender - Centre-Back',
  'club': 'Bor. Dortmund'},
 {'_id': ObjectId('69d50826639fbfcf435c01bc'),
  'name': 'Raphaël Guerreiro',
  'age': 29,
  'height': 1.7,
  'nationality': 'Portugal\xa0\xa0France',
  'price': 20000000,
  'max_price': 40000000,
  'position': 'Defender - Left-Back',
  'club': 'Bor. Dortmund'},
 {'_id': ObjectId('69d50826639fbfcf435c01bd'),
  'name': 'Giovanni Reyna',
  'age': 20,
  'height': 1.85,
  'nationality': 'United States\xa0\xa0Portugal',
  'price': 28000000,
  'max_price': 42000000,
  'position': 'midfield - Attacking Midfield',
  'club': 'Bor. Dortmund'},
 {'_id': ObjectId('69d50826639fbfcf435c01be'),
  'name': 'Karim Adeyemi',
  'age': 21,
  'height': 1.8,
  'nationality': 'Germany\xa0\xa0Nigeria',
  'price': 35000000,
  'max_price': 35000000,
  'position': 'Attack - Left Winger',
  'club': 'Bor. Dortmund'},
 {'_id': ObjectId('69d50826639fbfcf435c01bf'),
  'name': 'Sébastien Haller',
  'age': 28,
  'height': 1.91,
  'nationality': "Cote d'Ivoire\xa0\xa0France",
  'price': 30000000,
  'max_price': 45000000,
  'position': 'Attack - Centre-Forward',
  'club': 'Bor. Dortmund'},
 {'_id': ObjectId('69d50826639fbfcf435c01c0'),
  'name': 'Janis Blaswich',
  'age': 32,
  'height': 1.93,
  'nationality': 'Germany',
  'price': 2000000,
  'max_price': 2000000,
  'position': 'Goalkeeper',
  'club': 'RB Leipzig'},
 {'_id': ObjectId('69d50826639fbfcf435c01c1'),
  'name': 'Abdou Diallo',
  'age': 27,
  'height': 1.87,
  'nationality': 'Senegal\xa0\xa0France',
  'price': 15000000,
  'max_price': 35000000,
  'position': 'Defender - Centre-Back',
  'club': 'RB Leipzig'},
 {'_id': ObjectId('69d50826639fbfcf435c01c2'),
  'name': 'Willi Orbán',
  'age': 30,
  'height': 1.86,
  'nationality': 'Hungary\xa0\xa0Germany',
  'price': 10000000,
  'max_price': 20000000,
  'position': 'Defender - Centre-Back',
  'club': 'RB Leipzig'},
 {'_id': ObjectId('69d50826639fbfcf435c01c3'),
  'name': 'Christopher Nkunku',
  'age': 25,
  'height': 1.78,
  'nationality': 'France\xa0\xa0DR Congo',
  'price': 80000000,
  'max_price': 80000000,
  'position': 'Attack - Second Striker',
  'club': 'RB Leipzig'},
 {'_id': ObjectId('69d50826639fbfcf435c01c4'),
  'name': 'André Silva',
  'age': 27,
  'height': 1.85,
  'nationality': 'Portugal',
  'price': 20000000,
  'max_price': 45000000,
  'position': 'Attack - Centre-Forward',
  'club': 'RB Leipzig'},
 {'_id': ObjectId('69d50826639fbfcf435c01c5'),
  'name': 'Piero Hincapié',
  'age': 21,
  'height': 1.83,
  'nationality': 'Ecuador',
  'price': 25000000,
  'max_price': 25000000,
  'position': 'Defender - Centre-Back',
  'club': 'B. Leverkusen'},
 {'_id': ObjectId('69d50826639fbfcf435c01c6'),
  'name': 'Jonathan Tah',
  'age': 27,
  'height': 1.95,
  'nationality': 'Germany',
  'price': 20000000,
  'max_price': 40000000,
  'position': 'Defender - Centre-Back',
  'club': 'B. Leverkusen'},
 {'_id': ObjectId('69d50826639fbfcf435c01c7'),
  'name': 'Jeremie Frimpong',
  'age': 22,
  'height': 1.71,
  'nationality': 'Netherlands\xa0\xa0Ghana',
  'price': 35000000,
  'max_price': 35000000,
  'position': 'Defender - Right-Back',
  'club': 'B. Leverkusen'},
 {'_id': ObjectId('69d50826639fbfcf435c01c8'),
  'name': 'Florian Wirtz',
  'age': 20,
  'height': 1.76,
  'nationality': 'Germany',
  'price': 85000000,
  'max_price': 85000000,
  'position': 'midfield - Attacking Midfield',
  'club': 'B. Leverkusen'},
 {'_id': ObjectId('69d50826639fbfcf435c01c9'),
  'name': 'Callum Hudson-Odoi',
  'age': 22,
  'height': 1.77,
  'nationality': 'England\xa0\xa0Ghana',
  'price': 17000000,
  'max_price': 35000000,
  'position': 'Attack - Left Winger',
  'club': 'B. Leverkusen'},
 {'_id': ObjectId('69d50826639fbfcf435c01ca'),
  'name': 'Adam Hlozek',
  'age': 20,
  'height': 1.88,
  'nationality': 'Czech Republic',
  'price': 15000000,
  'max_price': 20000000,
  'position': 'Attack - Centre-Forward',
  'club': 'B. Leverkusen'},
 {'_id': ObjectId('69d50826639fbfcf435c01cb'),
  'name': 'Sardar Azmoun',
  'age': 28,
  'height': 1.86,
  'nationality': 'Iran',
  'price': 12000000,
  'max_price': 25000000,
  'position': 'Attack - Centre-Forward',
  'club': 'B. Leverkusen'},
 {'_id': ObjectId('69d50826639fbfcf435c01cc'),
  'name': 'Kevin Trapp',
  'age': 32,
  'height': 1.89,
  'nationality': 'Germany',
  'price': 8500000,
  'max_price': 12000000,
  'position': 'Goalkeeper',
  'club': 'E. Frankfurt'},
 {'_id': ObjectId('69d50826639fbfcf435c01cd'),
  'name': 'Makoto Hasebe',
  'age': 39,
  'height': 1.8,
  'nationality': 'Japan',
  'price': 800000,
  'max_price': 5000000,
  'position': 'Defender - Centre-Back',
  'club': 'E. Frankfurt'},
 {'_id': ObjectId('69d50826639fbfcf435c01ce'),
  'name': 'Daichi Kamada',
  'age': 26,
  'height': 1.84,
  'nationality': 'Japan',
  'price': 30000000,
  'max_price': 30000000,
  'position': 'midfield - Attacking Midfield',
  'club': 'E. Frankfurt'},
 {'_id': ObjectId('69d50826639fbfcf435c01cf'),
  'name': 'Jesper Lindström',
  'age': 23,
  'height': 1.82,
  'nationality': 'Denmark',
  'price': 28000000,
  'max_price': 28000000,
  'position': 'midfield - Attacking Midfield',
  'club': 'E. Frankfurt'},
 {'_id': ObjectId('69d50826639fbfcf435c01d0'),
  'name': 'Lucas Alario',
  'age': 30,
  'height': 1.85,
  'nationality': 'Argentina\xa0\xa0Italy',
  'price': 4000000,
  'max_price': 20000000,
  'position': 'Attack - Centre-Forward',
  'club': 'E. Frankfurt'},
 {'_id': ObjectId('69d50826639fbfcf435c01d1'),
  'name': 'Jan Olschowsky',
  'age': 21,
  'height': 1.84,
  'nationality': 'Germany',
  'price': 500000,
  'max_price': 500000,
  'position': 'Goalkeeper',
  'club': "Bor. M'gladbach"},
 {'_id': ObjectId('69d50826639fbfcf435c01d2'),
  'name': 'Ko Itakura',
  'age': 26,
  'height': 1.88,
  'nationality': 'Japan',
  'price': 12000000,
  'max_price': 12000000,
  'position': 'Defender - Centre-Back',
  'club': "Bor. M'gladbach"},
 {'_id': ObjectId('69d50826639fbfcf435c01d3'),
  'name': 'Joe Scally',
  'age': 20,
  'height': 1.84,
  'nationality': 'United States',
  'price': 12000000,
  'max_price': 12000000,
  'position': 'Defender - Right-Back',
  'club': "Bor. M'gladbach"},
 {'_id': ObjectId('69d50826639fbfcf435c01d4'),
  'name': 'Manu Koné',
  'age': 21,
  'height': 1.85,
  'nationality': "France\xa0\xa0Cote d'Ivoire",
  'price': 30000000,
  'max_price': 30000000,
  'position': 'midfield - Central Midfield',
  'club': "Bor. M'gladbach"},
 {'_id': ObjectId('69d50826639fbfcf435c01d5'),
  'name': 'Oscar Fraulo',
  'age': 19,
  'height': 1.8,
  'nationality': 'Denmark\xa0\xa0Italy',
  'price': 2000000,
  'max_price': 2000000,
  'position': 'midfield - Central Midfield',
  'club': "Bor. M'gladbach"},
 {'_id': ObjectId('69d50826639fbfcf435c01d6'),
  'name': 'Nathan Ngoumou',
  'age': 23,
  'height': 1.83,
  'nationality': 'France\xa0\xa0Cameroon',
  'price': 5000000,
  'max_price': 7000000,
  'position': 'Attack - Right Winger',
  'club': "Bor. M'gladbach"},
 {'_id': ObjectId('69d50826639fbfcf435c01d7'),
  'name': 'Marcus Thuram',
  'age': 25,
  'height': 1.92,
  'nationality': 'France\xa0\xa0Guadeloupe',
  'price': 32000000,
  'max_price': 40000000,
  'position': 'Attack - Centre-Forward',
  'club': "Bor. M'gladbach"},
 {'_id': ObjectId('69d50826639fbfcf435c01d8'),
  'name': 'Ridle Baku',
  'age': 25,
  'height': 1.76,
  'nationality': 'Germany\xa0\xa0DR Congo',
  'price': 13000000,
  'max_price': 25000000,
  'position': 'Defender - Right-Back',
  'club': 'VfL Wolfsburg'},
 {'_id': ObjectId('69d50826639fbfcf435c01d9'),
  'name': 'Jakub Kaminski',
  'age': 20,
  'height': 1.79,
  'nationality': 'Poland',
  'price': 10000000,
  'max_price': 10000000,
  'position': 'Attack - Left Winger',
  'club': 'VfL Wolfsburg'},
 {'_id': ObjectId('69d50826639fbfcf435c01da'),
  'name': 'Ozan Kabak',
  'age': 23,
  'height': 1.87,
  'nationality': 'Turkey',
  'price': 10000000,
  'max_price': 32000000,
  'position': 'Defender - Centre-Back',
  'club': 'TSG Hoffenheim'},
 {'_id': ObjectId('69d50826639fbfcf435c01db'),
  'name': 'Kevin Akpoguma',
  'age': 28,
  'height': 1.92,
  'nationality': 'Nigeria\xa0\xa0Germany',
  'price': 4000000,
  'max_price': 12000000,
  'position': 'Defender - Centre-Back',
  'club': 'TSG Hoffenheim'},
 {'_id': ObjectId('69d50826639fbfcf435c01dc'),
  'name': 'Eduardo Quaresma',
  'age': 21,
  'height': 1.85,
  'nationality': 'Portugal',
  'price': 3000000,
  'max_price': 7000000,
  'position': 'Defender - Centre-Back',
  'club': 'TSG Hoffenheim'},
 {'_id': ObjectId('69d50826639fbfcf435c01dd'),
  'name': 'Ermin Bicakcic',
  'age': 33,
  'height': 1.85,
  'nationality': 'Bosnia-Herzegovina\xa0\xa0Germany',
  'price': 1000000,
  'max_price': 4000000,
  'position': 'Defender - Centre-Back',
  'club': 'TSG Hoffenheim'},
 {'_id': ObjectId('69d50826639fbfcf435c01de'),
  'name': 'Justin Che',
  'age': 19,
  'height': 1.85,
  'nationality': 'United States\xa0\xa0Germany',
  'price': 2000000,
  'max_price': 3000000,
  'position': 'Defender - Right-Back',
  'club': 'TSG Hoffenheim'},
 {'_id': ObjectId('69d50826639fbfcf435c01df'),
  'name': 'Umut Tohumcu',
  'age': 18,
  'height': 1.75,
  'nationality': 'Germany\xa0\xa0Turkey',
  'price': 1000000,
  'max_price': 1000000,
  'position': 'midfield - Central Midfield',
  'club': 'TSG Hoffenheim'},
 {'_id': ObjectId('69d50826639fbfcf435c01e0'),
  'name': 'Kasper Dolberg',
  'age': 25,
  'height': 1.87,
  'nationality': 'Denmark',
  'price': 9000000,
  'max_price': 23000000,
  'position': 'Attack - Centre-Forward',
  'club': 'TSG Hoffenheim'},
 {'_id': ObjectId('69d50826639fbfcf435c01e1'),
  'name': 'Munas Dabbur',
  'age': 30,
  'height': 1.82,
  'nationality': 'Israel',
  'price': 4000000,
  'max_price': 15000000,
  'position': 'Attack - Centre-Forward',
  'club': 'TSG Hoffenheim'},
 {'_id': ObjectId('69d50826639fbfcf435c01e2'),
  'name': 'Frederik Rönnow',
  'age': 30,
  'height': 1.88,
  'nationality': 'Denmark',
  'price': 3500000,
  'max_price': 3500000,
  'position': 'Goalkeeper',
  'club': 'Union Berlin'},
 {'_id': ObjectId('69d50826639fbfcf435c01e3'),
  'name': 'Rafal Gikiewicz',
  'age': 35,
  'height': 1.9,
  'nationality': 'Poland',
  'price': 1200000,
  'max_price': 1500000,
  'position': 'Goalkeeper',
  'club': 'FC Augsburg'},
 {'_id': ObjectId('69d50826639fbfcf435c01e4'),
  'name': 'Felix Uduokhai',
  'age': 25,
  'height': 1.92,
  'nationality': 'Germany\xa0\xa0Nigeria',
  'price': 10000000,
  'max_price': 16000000,
  'position': 'Defender - Centre-Back',
  'club': 'FC Augsburg'},
 {'_id': ObjectId('69d50826639fbfcf435c01e5'),
  'name': 'Mads Pedersen',
  'age': 26,
  'height': 1.74,
  'nationality': 'Denmark',
  'price': 2500000,
  'max_price': 2500000,
  'position': 'Defender - Left-Back',
  'club': 'FC Augsburg'},
 {'_id': ObjectId('69d50826639fbfcf435c01e6'),
  'name': 'David Colina',
  'age': 22,
  'height': 1.74,
  'nationality': 'Croatia',
  'price': 1500000,
  'max_price': 1500000,
  'position': 'Defender - Left-Back',
  'club': 'FC Augsburg'},
 {'_id': ObjectId('69d50826639fbfcf435c01e7'),
  'name': 'Ermedin Demirovic',
  'age': 25,
  'height': 1.85,
  'nationality': 'Bosnia-Herzegovina\xa0\xa0Germany',
  'price': 12000000,
  'max_price': 12000000,
  'position': 'Attack - Centre-Forward',
  'club': 'FC Augsburg'},
 {'_id': ObjectId('69d50826639fbfcf435c01e8'),
  'name': 'Waldemar Anton',
  'age': 26,
  'height': 1.89,
  'nationality': 'Germany',
  'price': 4500000,
  'max_price': 15000000,
  'position': 'Defender - Centre-Back',
  'club': 'VfB Stuttgart'},
 {'_id': ObjectId('69d50826639fbfcf435c01e9'),
  'name': 'Josha Vagnoman',
  'age': 22,
  'height': 1.9,
  'nationality': "Germany\xa0\xa0Cote d'Ivoire",
  'price': 5000000,
  'max_price': 5000000,
  'position': 'Defender - Right-Back',
  'club': 'VfB Stuttgart'},
 {'_id': ObjectId('69d50826639fbfcf435c01ea'),
  'name': 'Wataru Endo',
  'age': 30,
  'height': 1.78,
  'nationality': 'Japan',
  'price': 6500000,
  'max_price': 10000000,
  'position': 'midfield - Defensive Midfield',
  'club': 'VfB Stuttgart'},
 {'_id': ObjectId('69d50826639fbfcf435c01eb'),
  'name': 'Genki Haraguchi',
  'age': 32,
  'height': 1.78,
  'nationality': 'Japan',
  'price': 2000000,
  'max_price': 4500000,
  'position': 'midfield - Attacking Midfield',
  'club': 'VfB Stuttgart'},
 {'_id': ObjectId('69d50826639fbfcf435c01ec'),
  'name': 'Ömer Beyaz',
  'age': 19,
  'height': 1.71,
  'nationality': 'Turkey',
  'price': 700000,
  'max_price': 1000000,
  'position': 'midfield - Attacking Midfield',
  'club': 'VfB Stuttgart'},
 {'_id': ObjectId('69d50826639fbfcf435c01ed'),
  'name': 'Gil Dias',
  'age': 26,
  'height': 1.86,
  'nationality': 'Portugal',
  'price': 2000000,
  'max_price': 4000000,
  'position': 'Attack - Right Winger',
  'club': 'VfB Stuttgart'},
 {'_id': ObjectId('69d50826639fbfcf435c01ee'),
  'name': 'Juan José Perea',
  'age': 23,
  'height': 1.8,
  'nationality': 'Colombia',
  'price': 2400000,
  'max_price': 2400000,
  'position': 'Attack - Centre-Forward',
  'club': 'VfB Stuttgart'},
 {'_id': ObjectId('69d50826639fbfcf435c01ef'),
  'name': 'Danny da Costa',
  'age': 29,
  'height': 1.87,
  'nationality': 'Germany\xa0\xa0Angola',
  'price': 2000000,
  'max_price': 15000000,
  'position': 'Defender - Right-Back',
  'club': '1.FSV Mainz 05'},
 {'_id': ObjectId('69d50826639fbfcf435c01f0'),
  'name': 'Marlon Mustapha',
  'age': 21,
  'height': 1.85,
  'nationality': 'Austria',
  'price': 1000000,
  'max_price': 1000000,
  'position': 'Attack - Centre-Forward',
  'club': '1.FSV Mainz 05'},
 {'_id': ObjectId('69d50826639fbfcf435c01f1'),
  'name': 'Denis Huseinbasic',
  'age': 21,
  'height': 1.84,
  'nationality': 'Germany\xa0\xa0Bosnia-Herzegovina',
  'price': 5000000,
  'max_price': 5000000,
  'position': 'midfield - Central Midfield',
  'club': '1.FC Köln'},
 {'_id': ObjectId('69d50826639fbfcf435c01f2'),
  'name': 'Filip Uremovic',
  'age': 26,
  'height': 1.84,
  'nationality': 'Croatia',
  'price': 2000000,
  'max_price': 7000000,
  'position': 'Defender - Centre-Back',
  'club': 'Hertha BSC'},
 {'_id': ObjectId('69d50826639fbfcf435c01f3'),
  'name': 'Dodi Lukébakio',
  'age': 25,
  'height': 1.87,
  'nationality': 'Belgium\xa0\xa0DR Congo',
  'price': 12000000,
  'max_price': 21000000,
  'position': 'Attack - Right Winger',
  'club': 'Hertha BSC'},
 {'_id': ObjectId('69d50826639fbfcf435c01f4'),
  'name': 'Jens Stage',
  'age': 26,
  'height': 1.87,
  'nationality': 'Denmark',
  'price': 3500000,
  'max_price': 4000000,
  'position': 'midfield - Central Midfield',
  'club': 'Werder Bremen'},
 {'_id': ObjectId('69d50826639fbfcf435c01f5'),
  'name': 'Niklas Schmidt',
  'age': 25,
  'height': 1.84,
  'nationality': 'Germany',
  'price': 2500000,
  'max_price': 2500000,
  'position': 'midfield - Attacking Midfield',
  'club': 'Werder Bremen'},
 {'_id': ObjectId('69d50826639fbfcf435c01f6'),
  'name': 'Ralf Fährmann',
  'age': 34,
  'height': 1.97,
  'nationality': 'Germany',
  'price': 400000,
  'max_price': 13000000,
  'position': 'Goalkeeper',
  'club': 'FC Schalke 04'},
 {'_id': ObjectId('69d50826639fbfcf435c01f7'),
  'name': 'Maya Yoshida',
  'age': 34,
  'height': 1.89,
  'nationality': 'Japan',
  'price': 1500000,
  'max_price': 7000000,
  'position': 'Defender - Centre-Back',
  'club': 'FC Schalke 04'},
 {'_id': ObjectId('69d50826639fbfcf435c01f8'),
  'name': 'Alex Kral',
  'age': 24,
  'height': 1.86,
  'nationality': 'Czech Republic\xa0\xa0Slovakia',
  'price': 5500000,
  'max_price': 10000000,
  'position': 'midfield - Defensive Midfield',
  'club': 'FC Schalke 04'},
 {'_id': ObjectId('69d50826639fbfcf435c01f9'),
  'name': 'Takuma Asano',
  'age': 28,
  'height': 1.73,
  'nationality': 'Japan',
  'price': 4000000,
  'max_price': 4000000,
  'position': 'Attack - Right Winger',
  'club': 'VfL Bochum'},
 {'_id': ObjectId('69d50826639fbfcf435c01fa'),
  'name': 'Simon Zoller',
  'age': 31,
  'height': 1.79,
  'nationality': 'Germany',
  'price': 1100000,
  'max_price': 3000000,
  'position': 'Attack - Centre-Forward',
  'club': 'VfL Bochum'},
 {'_id': ObjectId('69d50826639fbfcf435c01fb'),
  'name': 'Silvère Ganvoula',
  'age': 26,
  'height': 1.91,
  'nationality': 'Congo',
  'price': 750000,
  'max_price': 2500000,
  'position': 'Attack - Centre-Forward',
  'club': 'VfL Bochum'}]

In [26]:
len(list(collection.find({"height" : {"$lt" : 1.90}})))

62

In [27]:
len(list(collection.find({"age" : {"$gt" : 35}})))

2

In [28]:
results = list(collection.find({"nationality": "Germany"}).sort("age", 1).limit(10))

results

[{'_id': ObjectId('69d50826639fbfcf435c01c8'),
  'name': 'Florian Wirtz',
  'age': 20,
  'height': 1.76,
  'nationality': 'Germany',
  'price': 85000000,
  'max_price': 85000000,
  'position': 'midfield - Attacking Midfield',
  'club': 'B. Leverkusen'},
 {'_id': ObjectId('69d50826639fbfcf435c01d1'),
  'name': 'Jan Olschowsky',
  'age': 21,
  'height': 1.84,
  'nationality': 'Germany',
  'price': 500000,
  'max_price': 500000,
  'position': 'Goalkeeper',
  'club': "Bor. M'gladbach"},
 {'_id': ObjectId('69d50826639fbfcf435c01f5'),
  'name': 'Niklas Schmidt',
  'age': 25,
  'height': 1.84,
  'nationality': 'Germany',
  'price': 2500000,
  'max_price': 2500000,
  'position': 'midfield - Attacking Midfield',
  'club': 'Werder Bremen'},
 {'_id': ObjectId('69d50826639fbfcf435c01e8'),
  'name': 'Waldemar Anton',
  'age': 26,
  'height': 1.89,
  'nationality': 'Germany',
  'price': 4500000,
  'max_price': 15000000,
  'position': 'Defender - Centre-Back',
  'club': 'VfB Stuttgart'},
 {'_id': ObjectId('69d50826639fbfcf435c01c6'),
  'name': 'Jonathan Tah',
  'age': 27,
  'height': 1.95,
  'nationality': 'Germany',
  'price': 20000000,
  'max_price': 40000000,
  'position': 'Defender - Centre-Back',
  'club': 'B. Leverkusen'},
 {'_id': ObjectId('69d50826639fbfcf435c01fa'),
  'name': 'Simon Zoller',
  'age': 31,
  'height': 1.79,
  'nationality': 'Germany',
  'price': 1100000,
  'max_price': 3000000,
  'position': 'Attack - Centre-Forward',
  'club': 'VfL Bochum'},
 {'_id': ObjectId('69d50826639fbfcf435c01c0'),
  'name': 'Janis Blaswich',
  'age': 32,
  'height': 1.93,
  'nationality': 'Germany',
  'price': 2000000,
  'max_price': 2000000,
  'position': 'Goalkeeper',
  'club': 'RB Leipzig'},
 {'_id': ObjectId('69d50826639fbfcf435c01cc'),
  'name': 'Kevin Trapp',
  'age': 32,
  'height': 1.89,
  'nationality': 'Germany',
  'price': 8500000,
  'max_price': 12000000,
  'position': 'Goalkeeper',
  'club': 'E. Frankfurt'},
 {'_id': ObjectId('69d50826639fbfcf435c01bb'),
  'name': 'Mats Hummels',
  'age': 34,
  'height': 1.91,
  'nationality': 'Germany',
  'price': 6500000,
  'max_price': 60000000,
  'position': 'Defender - Centre-Back',
  'club': 'Bor. Dortmund'},
 {'_id': ObjectId('69d50826639fbfcf435c01f6'),
  'name': 'Ralf Fährmann',
  'age': 34,
  'height': 1.97,
  'nationality': 'Germany',
  'price': 400000,
  'max_price': 13000000,
  'position': 'Goalkeeper',
  'club': 'FC Schalke 04'}]

ODM APPROACH

In [29]:
# pip install mongoengine

In [30]:
from mongoengine import connect

connect(
    db   = "bundesliga",
    host = "mongodb://admin:123@localhost:27017/?authSource=admin"
)

try:
    client = MongoClient("mongodb://admin:123@localhost:27017/?authSource=admin")
    client.server_info()
    print("Connected to MongoDB successfully !!!")
except Exception as e:
    print("Connection failed: ", e)

Connected to MongoDB successfully !!!

In [31]:
### Defining the model
from mongoengine import Document, StringField, IntField, FloatField

class Players(Document):
    name        = StringField(required = True)
    age         = IntField()
    height      = FloatField()
    nationality = StringField()
    price       = IntField()
    max_price   = IntField()
    position    = StringField()
    club        = StringField()

In [32]:
# for record in records:
#     record.pop('_id', None)
#     player = Players(**record)
#     player.save()

In [33]:
Players.objects()

[<Players: Players object>, <Players: Players object>, <Players: Players object>, <Players: Players object>, <Players: Players object>, <Players: Players object>, <Players: Players object>, <Players: Players object>, <Players: Players object>, <Players: Players object>, <Players: Players object>, <Players: Players object>, <Players: Players object>, <Players: Players object>, <Players: Players object>, <Players: Players object>, <Players: Players object>, <Players: Players object>, <Players: Players object>, <Players: Players object>, '...(remaining elements truncated)...']

In [39]:
start = time.perf_counter()

player = Players.objects().first()
player = Players.objects(age__gte=25, club = "Bor. Dortmund", position__icontains = "Forward").limit(10)
for p in player:
    print(p.name, p.age, p.position)

end   = time.perf_counter()
time_taken = end - start
print(f"It took {time_taken * 1000:.2f} ms to perform this query")

Sébastien Haller 28 Attack - Centre-Forward
It took 2.62 ms to perform this query

In [41]:
Players.objects(age__lt = 20).delete()

0

In [42]:
Players.objects(name = "Dayot Upamecano").update(set__age = 25)

1

In [48]:
new_player = Players(
    name = "Harry Kane",
    age  = 30,
    height = 1.88,
    nationality = "England",
    price = 100000000,
    max_price = 150000000,
    position = "Attack - Centre-Forward",
    club = "Bayern Munich"
)

new_player.save()